import {buildMoovitDirectionsUrl,buildMoovitNearbyUrl,validPlace} from './features-core.js';
const FEATURE_KEY='foco-jornada-features-v2';
const MOOVIT_PARTNER_ID='FocoJornada';
const $=s=>document.querySelector(s);
const readFeature=()=>{try{return JSON.parse(localStorage.getItem(FEATURE_KEY)||'{}')||{}}catch{return{}}};
const writeFeature=v=>localStorage.setItem(FEATURE_KEY,JSON.stringify(v));
const placeLabel=(key,f)=>key==='current'?'Localização atual':f?.places?.[key]?.name||(key==='home'?'Casa':'Trabalho');
const resolvePlace=(key,f)=>key==='current'?null:(validPlace(f?.places?.[key])?f.places[key]:null);
function ensureStyles(){if($('#appLinksStyles'))return;const s=document.createElement('style');s.id='appLinksStyles';s.textContent='.app-link-status{margin:10px 0 0;padding:11px 12px;border:1px solid var(--line);border-radius:14px;background:var(--surface2);color:var(--muted);font-size:13px;line-height:1.45}.app-link-status.error{color:var(--danger)}.native-app-link{display:flex!important;align-items:center;justify-content:center;gap:8px;text-decoration:none!important}';document.head.appendChild(s)}
function routeStatus(text,type=''){const host=$('#planMoovit');if(!host)return;let el=$('#appLinkRouteStatus');if(!el){el=document.createElement('div');el.id='appLinkRouteStatus';host.after(el)}el.className=`app-link-status ${type}`.trim();el.textContent=text}
function revealPlaces(){const d=$('#moovitSection details.transport-settings');if(d){d.open=true;d.scrollIntoView({behavior:'smooth',block:'nearest'})}}
function validateRoute(origin,dest,f){if(origin===dest){routeStatus('Escolhe uma origem e um destino diferentes.','error');return false}if(origin!=='current'&&!resolvePlace(origin,f)){routeStatus(`Falta configurar ${placeLabel(origin,f)}.`,'error');revealPlaces();return false}if(dest!=='current'&&!resolvePlace(dest,f)){routeStatus(`Falta configurar ${placeLabel(dest,f)}.`,'error');revealPlaces();return false}return true}
function rememberTrip(origin,dest,when,f){const trip={id:`trip_${Date.now()}`,originKey:origin,destKey:dest,originLabel:placeLabel(origin,f),destinationLabel:placeLabel(dest,f),when:when?new Date(when).toISOString():null,at:Date.now()};f.recentTrips=[trip,...(Array.isArray(f.recentTrips)?f.recentTrips:[])].slice(0,10);writeFeature(f)}
function replacePlan(){const old=$('#planMoovit');if(!old||old.dataset.nativeLink==='1')return;const a=document.createElement('a');a.id='planMoovit';a.className=old.className+' native-app-link';a.innerHTML=old.innerHTML;a.href='#';a.dataset.nativeLink='1';old.replaceWith(a);a.onclick=e=>{const f=readFeature(),origin=$('#routeOrigin')?.value||'current',dest=$('#routeDestination')?.value||'work',when=$('#routeWhen')?.value||null;if(!validateRoute(origin,dest,f)){e.preventDefault();return}a.href=buildMoovitDirectionsUrl({origin:resolvePlace(origin,f),destination:resolvePlace(dest,f),date:when||null,autoRun:true,partnerId:MOOVIT_PARTNER_ID});rememberTrip(origin,dest,when,f);routeStatus('A abrir a rota no Moovit…')}}
function replaceNearby(){const old=$('#nearbyTransit');if(!old||old.dataset.nativeLink==='1')return;const a=document.createElement('a');a.id='nearbyTransit';a.className=old.className+' native-app-link';a.innerHTML=old.innerHTML;a.href=buildMoovitNearbyUrl({partnerId:MOOVIT_PARTNER_ID});a.dataset.nativeLink='1';old.replaceWith(a)}
function replaceSupershift(){const old=$('#openSupershift');if(!old||old.dataset.internalPlanner==='1')return;old.dataset.internalPlanner='1';old.textContent='Abrir calendário e turnos';old.onclick=async e=>{e.preventDefault();try{if(window.FocoShiftPlanner?.open)return window.FocoShiftPlanner.open();const mod=await import('./shift-planner.js');mod.open()}catch{window.FocoUI?.notify?.('Não foi possível abrir a escala.')}}}
function enhance(){ensureStyles();replacePlan();replaceNearby();replaceSupershift()}
let raf=0;const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;enhance()})};new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();window.FocoAppLinks=Object.freeze({version:'2.0.0',enhance});
