import {DEFAULT_COUPLE_SCHEDULE,couplePlan,coupleStateForNow,nextCoupleReminderAt,recordCoupleAction,localDayKey} from './couple-core.js';

const FEATURE_KEY='foco-jornada-features-v2';
const APP_KEY='foco-jornada-v4';
const $=s=>document.querySelector(s);
let reminderTimer=null;

const heart='<path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z"/>';
const clock='<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>';
const check='<path d="m5 12 4 4L19 6"/>';
const svg=(body,cls='')=>`<svg class="couple-svg ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const dayNames=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];

function readFeature(){try{return JSON.parse(localStorage.getItem(FEATURE_KEY)||'{}')||{}}catch{return{}}}
function writeFeature(feature){localStorage.setItem(FEATURE_KEY,JSON.stringify(feature));window.dispatchEvent(new CustomEvent('foco-feature-change'))}
function coupleData(){const feature=readFeature(),current=feature.couple&&typeof feature.couple==='object'?feature.couple:{};return{enabled:current.enabled!==false,schedule:{...DEFAULT_COUPLE_SCHEDULE,...(current.schedule||{})},records:{...(current.records||{})}}}
function saveCouple(data){const feature=readFeature(),keys=Object.keys(data.records||{}).sort().slice(-120),records={};for(const key of keys)records[key]=data.records[key];feature.couple={enabled:data.enabled!==false,schedule:data.schedule||DEFAULT_COUPLE_SCHEDULE,records};writeFeature(feature)}
function appNotificationsEnabled(){try{return!!JSON.parse(localStorage.getItem(APP_KEY)||'null')?.settings?.notifications}catch{return false}}
function phaseLabel(phase){return({upcoming:'Hoje',active:'Agora',snoozed:'Adiado',done:'Concluído',skipped:'Ignorado hoje',ended:'Terminado'})[phase]||'Hoje'}
function notifyInternal(text){window.FocoUI?.notify?.(text,'Abrir',openCouplePanel)}
async function notifySystem(text){if(!appNotificationsEnabled()||!('Notification'in window)||Notification.permission!=='granted')return;try{const reg=await navigator.serviceWorker?.getRegistration();if(reg)await reg.showNotification('Tempo a dois',{body:text,tag:`couple-${localDayKey()}`,icon:'./icon.svg'})}catch{}}
function fireReminder(){const data=coupleData();if(!data.enabled)return;const now=Date.now(),status=coupleStateForNow(data.records,now,data.schedule);if(!['active','snoozed'].includes(status.phase)&&status.phase!=='upcoming'){scheduleReminder();return}if(status.phase==='upcoming'&&now<status.plan.startAt-1500){scheduleReminder();return}const text=`${status.plan.start}–${status.plan.end} · ${status.plan.title}.`;data.records=recordCoupleAction(data.records,'notified',now,data.schedule);saveCouple(data);notifyInternal(`Tempo a dois · ${text}`);notifySystem(text);renderAll();scheduleReminder()}
function scheduleReminder(){clearTimeout(reminderTimer);reminderTimer=null;const data=coupleData();if(!data.enabled)return;const now=Date.now(),at=nextCoupleReminderAt(data.records,now,data.schedule);if(!Number.isFinite(at))return;reminderTimer=setTimeout(fireReminder,Math.max(250,at-now))}
function act(action){const data=coupleData();data.records=recordCoupleAction(data.records,action,Date.now(),data.schedule);saveCouple(data);const msg=action==='done'?'Tempo a dois marcado como concluído.':action==='snooze'?'Lembrete adiado 30 minutos.':'Tempo a dois ignorado apenas hoje.';notifyInternal(msg);renderAll();scheduleReminder()}

function ensureTodayCard(){const host=$('[data-view="today"]'),hero=$('#todayHero');if(!host||!hero)return;let card=$('#coupleTodayCard');if(!card){card=document.createElement('section');card.id='coupleTodayCard';card.className='panel couple-today-card';const anchor=$('#journeyForecastCard')||hero;anchor.after(card)}const data=coupleData(),s=coupleStateForNow(data.records,Date.now(),data.schedule),p=s.plan;card.hidden=!data.enabled;if(card.hidden)return;card.innerHTML=`<div class="couple-card-icon">${svg(heart)}</div><div class="couple-card-copy"><span class="kicker">CASAMENTO · ${phaseLabel(s.phase)}</span><h2>${p.title}</h2><p>${p.start}–${p.end} · tempo protegido, sem transformar a relação numa tarefa.</p></div><button type="button" class="btn couple-open">Abrir</button>`;card.querySelector('.couple-open').onclick=openCouplePanel}
function ensureHubItem(){const hub=$('#appHub .hub-sheet');if(!hub||$('#coupleHubSection'))return;const appSection=hub.querySelector('.hub-app-section'),section=document.createElement('section');section.id='coupleHubSection';section.className='hub-group couple-hub-group';const p=couplePlan(Date.now(),coupleData().schedule);section.innerHTML=`<div class="hub-section-title"><span>Vida pessoal</span><small>Tempo protegido</small></div><button type="button" class="hub-row" id="hubCoupleButton"><span class="hub-row-icon couple-hub-icon">${svg(heart)}</span><span class="hub-row-copy"><b>Tempo a dois</b><small>Hoje · ${p.start}–${p.end}</small></span><span class="hub-row-arrow">›</span></button>`;appSection?.after(section);$('#hubCoupleButton').onclick=()=>{window.FocoHub?.close?.();openCouplePanel()}}
function ensurePanel(){if($('#couplePanel'))return;const root=document.createElement('section');root.id='couplePanel';root.className='couple-panel';root.hidden=true;root.innerHTML='<div class="couple-backdrop" data-couple-close></div><div class="couple-sheet" role="dialog" aria-modal="true" aria-labelledby="coupleTitle"></div>';document.body.appendChild(root);root.addEventListener('click',e=>{if(e.target.matches('[data-couple-close]'))closeCouplePanel()})}
function renderPanel(){ensurePanel();const sheet=$('#couplePanel .couple-sheet'),data=coupleData(),s=coupleStateForNow(data.records,Date.now(),data.schedule),p=s.plan;const rows=Object.entries(data.schedule).sort(([a],[b])=>Number(a)-Number(b)).map(([day,plan])=>`<div class="couple-schedule-row ${Number(day)===new Date().getDay()?'today':''}"><span>${dayNames[Number(day)]}</span><b>${plan.start}–${plan.end}</b><small>${plan.title}</small></div>`).join('');sheet.innerHTML=`<header class="couple-head"><div><span class="kicker">VIDA PESSOAL</span><h2 id="coupleTitle">Tempo a dois</h2><p>Um bloco protegido para o casamento, sem pontuação nem pressão.</p></div><button type="button" class="couple-close" data-couple-close aria-label="Fechar">×</button></header><section class="couple-hero"><span class="couple-heart">${svg(heart)}</span><div><small>HOJE · ${phaseLabel(s.phase)}</small><h3>${p.title}</h3><b>${p.start}–${p.end}</b></div></section><div class="couple-actions"><button type="button" class="btn primary" data-couple-action="done">${svg(check)} Concluído</button><button type="button" class="btn" data-couple-action="snooze">${svg(clock)} Adiar 30 min</button><button type="button" class="text-btn" data-couple-action="skip">Ignorar hoje</button></div><label class="couple-toggle"><input id="coupleEnabled" type="checkbox" ${data.enabled?'checked':''}><span><b>Lembretes de tempo a dois</b><small>Usa o sino interno e, se autorizado, a notificação do sistema.</small></span></label><section class="couple-week"><div class="couple-section-title"><span>Horário protegido</span><small>Quarta e sábado são os blocos principais.</small></div>${rows}</section><p class="couple-note">A aplicação apenas lembra. Não inicia nem conclui este tempo automaticamente.</p>`;sheet.querySelectorAll('[data-couple-action]').forEach(b=>b.onclick=()=>act(b.dataset.coupleAction));$('#coupleEnabled').onchange=e=>{const x=coupleData();x.enabled=e.target.checked;saveCouple(x);renderAll();scheduleReminder()}}
function openCouplePanel(){ensurePanel();renderPanel();const p=$('#couplePanel');p.hidden=false;document.body.classList.add('couple-open')}
function closeCouplePanel(){const p=$('#couplePanel');if(p)p.hidden=true;document.body.classList.remove('couple-open')}
function renderAll(){ensureTodayCard();ensureHubItem();if(!$('#couplePanel')?.hidden)renderPanel()}
function init(){ensurePanel();renderAll();scheduleReminder();document.addEventListener('visibilitychange',()=>{if(!document.hidden){renderAll();scheduleReminder()}});window.addEventListener('storage',e=>{if(e.key===FEATURE_KEY){renderAll();scheduleReminder()}});window.addEventListener('foco-feature-change',()=>{renderAll();scheduleReminder()})}
init();
window.FocoCouple=Object.freeze({open:openCouplePanel,close:closeCouplePanel,version:'1.0.0'});
