import {DEFAULT_COUPLE_CONFIG,normalizeCoupleConfig,couplePlan,coupleStateForNow,nextCoupleReminderAt,recordCoupleAction} from './couple-core.js';

const FEATURE_KEY='foco-jornada-features-v2';
const APP_KEY='foco-jornada-v4';
const $=s=>document.querySelector(s);
let reminderTimer=null;
const heart='<path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z"/>';
const clock='<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>';
const check='<path d="m5 12 4 4L19 6"/>';
const svg=(body,cls='')=>`<svg class="couple-svg ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const dayNames=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const fmtMinutes=m=>m>=60?`${Math.floor(m/60)}h${m%60?` ${m%60} min`:''}`:`${m} min`;

function ensureStyles(){if($('#coupleStyles'))return;const link=document.createElement('link');link.id='coupleStyles';link.rel='stylesheet';link.href='./couple.css';document.head.appendChild(link)}
function readFeature(){try{return JSON.parse(localStorage.getItem(FEATURE_KEY)||'{}')||{}}catch{return{}}}
function readApp(){try{return JSON.parse(localStorage.getItem(APP_KEY)||'null')}catch{return null}}
function writeFeature(feature){localStorage.setItem(FEATURE_KEY,JSON.stringify(feature));window.dispatchEvent(new CustomEvent('foco-feature-change'))}
function coupleData(){const feature=readFeature(),current=feature.couple&&typeof feature.couple==='object'?feature.couple:{};return{enabled:current.enabled!==false,config:normalizeCoupleConfig(current.config||DEFAULT_COUPLE_CONFIG),records:{...(current.records||{})}}}
function saveCouple(data){const feature=readFeature(),keys=Object.keys(data.records||{}).sort().slice(-120),records={};for(const key of keys)records[key]=data.records[key];feature.couple={enabled:data.enabled!==false,config:normalizeCoupleConfig(data.config),records};writeFeature(feature)}
function actualWorkEndAt(ts=Date.now()){const app=readApp(),d=new Date(ts),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return (app?.workSessions||[]).filter(w=>w.status!=='CANCELLED'&&Number.isFinite(w.endedAt)&&(()=>{const x=new Date(w.startedAt);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`===key})()).sort((a,b)=>b.endedAt-a.endedAt)[0]?.endedAt??null}
function planOptions(ts,data){const feature=readFeature();return{workSchedule:feature.schedule,actualWorkEndAt:actualWorkEndAt(ts),config:data.config}}
function planFor(ts=Date.now(),data=coupleData()){return couplePlan(ts,planOptions(ts,data))}
function stateFor(ts=Date.now(),data=coupleData()){return coupleStateForNow(data.records,ts,planOptions(ts,data))}
function appNotificationsEnabled(){return!!readApp()?.settings?.notifications}
function phaseLabel(p){return({upcoming:'Hoje',active:'Agora',snoozed:'Adiado',done:'Concluído',skipped:'Ignorado hoje',ended:'Terminado'})[p]||'Hoje'}
function notifyInternal(text){window.FocoUI?.notify?.(text,'Abrir',openCouplePanel)}
async function notifySystem(text){if(!appNotificationsEnabled()||!('Notification'in window)||Notification.permission!=='granted')return;try{const reg=await navigator.serviceWorker?.getRegistration();if(reg)await reg.showNotification('Tempo a dois',{body:text,tag:'couple-time',icon:'./icon.svg'})}catch{}}
function fireReminder(){const data=coupleData();if(!data.enabled)return;const now=Date.now(),opts=planOptions(now,data),status=coupleStateForNow(data.records,now,opts);if(status.phase==='done'||status.phase==='skipped'||status.phase==='ended'){scheduleReminder();return}if(status.phase==='upcoming'&&now<status.plan.reminderAt-1500){scheduleReminder();return}const text=`${status.plan.start}–${status.plan.end} · ${status.plan.title}.`;data.records=recordCoupleAction(data.records,'notified',now,opts);saveCouple(data);notifyInternal(`Tempo a dois · ${text}`);notifySystem(text);renderAll();scheduleReminder()}
function scheduleReminder(){clearTimeout(reminderTimer);reminderTimer=null;const data=coupleData();if(!data.enabled)return;const now=Date.now(),at=nextCoupleReminderAt(data.records,now,planOptions(now,data));if(!Number.isFinite(at))return;reminderTimer=setTimeout(fireReminder,Math.max(250,at-now))}
function act(action){const data=coupleData(),opts=planOptions(Date.now(),data);data.records=recordCoupleAction(data.records,action,Date.now(),opts);saveCouple(data);notifyInternal(action==='done'?'Tempo a dois marcado como concluído.':action==='snooze'?'Lembrete adiado 30 minutos.':'Tempo a dois ignorado apenas hoje.');renderAll();scheduleReminder()}
function planNote(p){return p.anchorSource==='actual'?'Ajustado à saída que registaste hoje.':`${p.bufferMinutes} min depois da saída prevista da jornada.`}

function ensureTodayCard(){const hero=$('#todayHero');if(!hero)return;let card=$('#coupleTodayCard');if(!card){card=document.createElement('section');card.id='coupleTodayCard';card.className='panel couple-today-card';($('#journeyForecastCard')||hero).after(card)}const data=coupleData(),s=stateFor(Date.now(),data),p=s.plan;card.hidden=!data.enabled;if(card.hidden)return;card.innerHTML=`<div class="couple-card-icon">${svg(heart)}</div><div class="couple-card-copy"><span class="kicker">VIDA PESSOAL · ${phaseLabel(s.phase)}</span><h2>${p.title}</h2><p>${p.start}–${p.end} · ${planNote(p)}</p></div><button type="button" class="btn couple-open">Abrir</button>`;card.querySelector('.couple-open').onclick=openCouplePanel}
function ensureHubItem(){const hub=$('#appHub .hub-sheet');if(!hub||$('#coupleHubSection'))return;const appSection=hub.querySelector('.hub-app-section'),section=document.createElement('section');section.id='coupleHubSection';section.className='hub-group couple-hub-group';section.innerHTML='<div class="hub-section-title"><span>Vida pessoal</span><small>Equilíbrio fora do trabalho</small></div><button type="button" class="hub-row" id="hubCoupleButton"><span class="hub-row-icon couple-hub-icon">'+svg(heart)+'</span><span class="hub-row-copy"><b>Tempo a dois</b><small data-couple-hub-time></small></span><span class="hub-row-arrow">›</span></button>';appSection?.after(section);$('#hubCoupleButton').onclick=()=>{window.FocoHub?.close?.();openCouplePanel()};refreshHubTime()}
function refreshHubTime(){const el=$('[data-couple-hub-time]');if(el){const p=planFor();el.textContent=`Hoje · ${p.start}–${p.end}`}}
function ensurePanel(){if($('#couplePanel'))return;const root=document.createElement('section');root.id='couplePanel';root.className='couple-panel';root.hidden=true;root.innerHTML='<div class="couple-backdrop" data-couple-close></div><div class="couple-sheet" role="dialog" aria-modal="true" aria-labelledby="coupleTitle"></div>';document.body.appendChild(root);root.addEventListener('click',e=>{if(e.target.matches('[data-couple-close]'))closeCouplePanel()})}
function weekRows(data){const now=new Date(),today=now.getDay();return[0,1,2,3,4,5,6].map(day=>{const d=new Date(now);d.setDate(now.getDate()+(day-today));d.setHours(12,0,0,0);const p=couplePlan(d.getTime(),{workSchedule:readFeature().schedule,config:data.config,actualWorkEndAt:null});return `<div class="couple-schedule-row ${day===today?'today':''}"><span>${dayNames[day]}</span><b>${p.start}</b><small>${fmtMinutes(p.durationMinutes)} · ${p.title}</small></div>`}).join('')}
function renderPanel(){ensurePanel();const sheet=$('#couplePanel .couple-sheet'),data=coupleData(),s=stateFor(Date.now(),data),p=s.plan;sheet.innerHTML=`<header class="couple-head"><div><span class="kicker">VIDA PESSOAL</span><h2 id="coupleTitle">Tempo a dois</h2><p>Protege o casamento sem transformar a relação numa lista de tarefas.</p></div><button type="button" class="couple-close" data-couple-close aria-label="Fechar">×</button></header><section class="couple-hero"><span class="couple-heart">${svg(heart)}</span><div><small>HOJE · ${phaseLabel(s.phase)}</small><h3>${p.title}</h3><b>${p.start}–${p.end}</b><em>${planNote(p)}</em></div></section><div class="couple-actions"><button type="button" class="btn primary" data-couple-action="done">${svg(check)} Concluído</button><button type="button" class="btn" data-couple-action="snooze">${svg(clock)} Adiar 30 min</button><button type="button" class="text-btn" data-couple-action="skip">Ignorar hoje</button></div><label class="couple-toggle"><input id="coupleEnabled" type="checkbox" ${data.enabled?'checked':''}><span><b>Lembrete discreto</b><small>Sino interno e notificação do sistema, quando autorizada.</small></span></label><label class="couple-setting"><span><b>Margem depois do trabalho</b><small>Tempo para deslocação, banho, jantar ou simplesmente desligar.</small></span><select id="coupleBuffer"><option value="60" ${data.config.bufferMinutes===60?'selected':''}>1 hora</option><option value="90" ${data.config.bufferMinutes===90?'selected':''}>1h30</option><option value="120" ${data.config.bufferMinutes===120?'selected':''}>2 horas</option></select></label><section class="couple-week"><div class="couple-section-title"><span>Plano equilibrado</span><small>Derivado do fim da jornada</small></div>${weekRows(data)}</section><p class="couple-note">Base: 30 min nos dias normais; quarta 1h30; sábado 3h; domingo 1h. Se terminares o trabalho mais tarde, o horário de hoje desloca-se automaticamente. A aplicação apenas lembra — nunca marca como concluído sozinha.</p>`;sheet.querySelectorAll('[data-couple-action]').forEach(b=>b.onclick=()=>act(b.dataset.coupleAction));$('#coupleEnabled').onchange=e=>{const x=coupleData();x.enabled=e.target.checked;saveCouple(x);renderAll();scheduleReminder()};$('#coupleBuffer').onchange=e=>{const x=coupleData();x.config={...x.config,bufferMinutes:Number(e.target.value)||90};saveCouple(x);renderAll();scheduleReminder();notifyInternal('Margem do tempo a dois atualizada.')}}
function openCouplePanel(){ensurePanel();renderPanel();const p=$('#couplePanel');p.hidden=false;document.body.classList.add('couple-open')}
function closeCouplePanel(){const p=$('#couplePanel');if(p)p.hidden=true;document.body.classList.remove('couple-open')}
function renderAll(){ensureTodayCard();ensureHubItem();refreshHubTime();if(!$('#couplePanel')?.hidden)renderPanel()}
function init(){ensureStyles();ensurePanel();renderAll();scheduleReminder();document.addEventListener('visibilitychange',()=>{if(!document.hidden){renderAll();scheduleReminder()}});window.addEventListener('storage',e=>{if([FEATURE_KEY,APP_KEY].includes(e.key)){renderAll();scheduleReminder()}});window.addEventListener('foco-feature-change',()=>{renderAll();scheduleReminder()})}
init();
window.FocoCouple=Object.freeze({open:openCouplePanel,close:closeCouplePanel,version:'2.0.0'});
