const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ico=body=>`<svg class="fj-help-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const I={
  close:'<path d="m6 6 12 12M18 6 6 18"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',
  start:'<path d="M5 4h14v16H5z"/><path d="M9 8h6M9 12h6M9 16h4"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  pause:'<circle cx="12" cy="12" r="9"/><path d="M9 8v8M15 8v8"/>',tasks:'<rect x="3" y="4" width="18" height="16" rx="3"/><path d="m8 10 2 2 4-4M15 10h3M8 16h10"/>',
  focus:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/>',coffee:'<path d="M4 8h12v8a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4Z"/><path d="M16 10h2a3 3 0 0 1 0 6h-2M7 4v2M11 4v2"/>',
  history:'<path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 4v5h5"/><path d="M12 7v5l3 2"/>',stats:'<path d="M4 20V10M10 20V4M16 20v-7M22 20V7"/>',
  bus:'<path d="M5 17h14l1-8c.2-2-1.2-4-3.3-4H7.3C5.2 5 3.8 7 4 9Z"/><path d="M7 17v2M17 17v2M7 12h10"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4M17 3v4M3 10h18"/>',
  bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/>',backup:'<path d="M5 4h11l3 3v13H5Z"/><path d="M8 4v6h8V4M8 20v-6h8v6"/>',
  update:'<path d="M20 7v5h-5"/><path d="M4 17v-5h5"/><path d="M18.5 9A7 7 0 0 0 6 6l-2 2M5.5 15A7 7 0 0 0 18 18l2-2"/>',
  wrench:'<path d="M14.7 6.3a4 4 0 0 0-5-5L12 3.6 8.6 7 6.3 4.7a4 4 0 0 0 5 5L4 17l3 3 7.3-7.3a4 4 0 0 0 5-5L17 10l-3.4-3.4Z"/>'
};

const HELP=[
  ['Primeiros passos','start',`<p>Usa <b>Hoje</b> como ponto de partida. Toca em <b>Entrar</b> para iniciar a jornada. A partir daí ficam disponíveis Pausa, Descanso, Foco e Café.</p><p>O menu <b>Mais</b> reúne escala, transportes, definições, backup, notificações, atualizações, Ajuda e Sobre.</p>`,'começar inicio entrar hoje menu'],
  ['Jornada de trabalho','clock',`<p><b>Entrar:</b> começa a contagem da jornada.</p><p><b>Terminar jornada:</b> encerra a sessão atual. Se existir pausa, foco ou atividade em curso, termina primeiro esse estado.</p><p><b>Histórico:</b> permite editar, reabrir ou eliminar definitivamente uma jornada.</p>`,'jornada trabalho entrar terminar sair eliminar reabrir editar'],
  ['Pausas e descanso','pause',`<p><b>Pausa</b> usa a duração de pausa de ecrã configurada. <b>Descanso</b> usa a pausa principal.</p><p>Se uma atividade estiver ativa, a pausa pode suspendê-la e sugerir retoma quando regressares.</p><p>As durações são configuradas em <b>Mais → Definições</b>.</p>`,'pausa descanso ecrã intervalo regressar duração'],
  ['Atividades','tasks',`<p>Em <b>Atividades</b> podes criar tarefas, definir prioridade, categoria, descrição e estimativa.</p><p>Uma atividade pode ser iniciada, pausada, concluída ou cancelada. Também pode ser associada a uma sessão Pomodoro.</p>`,'atividade tarefa prioridade categoria criar editar concluir cancelar'],
  ['Foco e Pomodoro','focus',`<p>Em <b>Foco</b>, escolhe opcionalmente uma atividade e toca em <b>Iniciar foco</b>.</p><p>Se ainda não houver jornada ativa, a aplicação pode iniciar Jornada + Foco em sequência.</p><p>Os tempos de foco, pausa curta, pausa longa e número de ciclos são configuráveis em Definições.</p>`,'foco pomodoro ciclo atividade iniciar pausar retomar'],
  ['Café','coffee',`<p>O botão <b>+ Café</b> regista uma unidade pelo preço configurado. O total diário e o gasto acumulado aparecem nas métricas e estatísticas.</p><p>O preço padrão pode ser alterado em <b>Mais → Definições</b>.</p>`,'café cafe preço vending gasto'],
  ['Histórico','history',`<p>Seleciona uma data para consultar a timeline e as jornadas desse dia.</p><p>Podes editar horários, reabrir uma jornada concluída ou <b>Eliminar</b> definitivamente uma jornada e os registos diretamente ligados a ela.</p>`,'histórico data timeline jornada eliminar editar'],
  ['Estatísticas','stats',`<p>Consulta 7 dias, 30 dias ou o ano. A aplicação mostra trabalho efetivo, foco, atividades concluídas e café.</p><p>O tempo de foco não é somado novamente como trabalho para evitar dupla contagem.</p>`,'estatísticas gráfico horas efetivo foco ano mês semana'],
  ['Moovit e transportes','bus',`<p>Em <b>Mais → Moovit</b> tens o planeador de transportes. Configura Casa e Trabalho e usa <b>Planear com Moovit</b> para abrir uma rota.</p><p><b>Perto de mim</b> tenta usar a localização atual. A abertura externa depende da aplicação Moovit e das permissões do iPhone.</p>`,'moovit transportes casa trabalho rota localização perto'],
  ['Supershift / Escala','calendar',`<p>O módulo interno de escala inclui Calendário, Relatórios, Turnos, Trabalhos e Rotações.</p><p>Toca num dia para atribuir ou alterar um turno. Em Relatórios podes configurar horas normais e salário/hora. Também existem exportação ICS e impressão/PDF A4.</p>`,'supershift escala calendário turno rotação relatório salário ics pdf'],
  ['Notificações','bell',`<p>Ativa as notificações em <b>Mais → Definições</b>. Usa <b>Testar notificação</b> para confirmar a permissão.</p><p>No iPhone, notificações de sistema dependem das permissões da PWA/Safari e das definições do dispositivo.</p>`,'notificação sino alerta permissão iphone testar'],
  ['Backup e dados','backup',`<p>Usa <b>Exportar backup</b> antes de limpar dados ou trocar de dispositivo. O ficheiro inclui os dados principais e módulos adicionais suportados.</p><p><b>Importar backup</b> apresenta um resumo antes da restauração. <b>Apagar dados</b> remove os dados locais deste dispositivo.</p>`,'backup exportar importar apagar dados restaurar diagnóstico'],
  ['Atualizações','update',`<p>Em <b>Mais → Atualizações</b> podes verificar uma nova versão da PWA. Quando existir uma versão pronta, escolhe <b>Atualizar agora</b>.</p><p>Se o visual continuar antigo, fecha completamente a PWA/Safari e abre novamente para renovar o cache.</p>`,'atualização versão cache service worker pwa'],
  ['Se algo não funcionar','wrench',`<p>1. Abre <b>Mais → Sobre</b> e verifica Rede, Service Worker e versão.</p><p>2. Em <b>Backup e diagnóstico</b>, usa <b>Verificar dados</b>.</p><p>3. Para notificações, confirma a permissão do sistema. Para Moovit, confirma localização e aplicação instalada.</p><p>4. Se uma atualização não aparecer, fecha e reabre a PWA.</p>`,'erro problema não funciona diagnóstico ajuda resolver cache']
];

function injectStyle(){if($('#fjHelpStyle'))return;const s=document.createElement('style');s.id='fjHelpStyle';s.textContent=`.fj-help{position:absolute;inset:0;z-index:8;background:var(--bg);overflow:auto;-webkit-overflow-scrolling:touch;padding:max(20px,env(safe-area-inset-top)) 20px max(28px,env(safe-area-inset-bottom));transform:translateX(102%);transition:transform .2s cubic-bezier(.2,.8,.2,1)}.fj-help.open{transform:none}.fj-help-head{position:sticky;top:-20px;z-index:2;background:color-mix(in srgb,var(--bg) 96%,transparent);backdrop-filter:blur(18px);display:flex;align-items:center;justify-content:space-between;gap:14px;padding:20px 0 14px;border-bottom:1px solid var(--line)}.fj-help-head h3{font-size:27px;margin:3px 0}.fj-help-close{width:40px;height:40px;border-radius:50%;border:1px solid var(--line);background:var(--surface2);color:var(--text);display:grid;place-items:center}.fj-help-svg{width:22px;height:22px}.fj-help-search{height:46px;margin:14px 0;display:grid;grid-template-columns:22px 1fr;align-items:center;gap:9px;border:1px solid var(--line);border-radius:15px;background:var(--surface2);padding:0 13px;color:var(--muted)}.fj-help-search input{border:0!important;background:transparent!important;color:var(--text)!important;outline:0;width:100%;font-size:14px!important;padding:0!important;min-height:0!important}.fj-help-intro{color:var(--muted);font-size:13px;line-height:1.5;margin:0 0 12px}.fj-help-list{display:grid;gap:8px}.fj-help-item{border:1px solid var(--line);border-radius:17px;background:var(--surface);overflow:hidden}.fj-help-item>summary{list-style:none;display:grid;grid-template-columns:32px 1fr auto;align-items:center;gap:10px;padding:13px 14px;cursor:pointer}.fj-help-item>summary::-webkit-details-marker{display:none}.fj-help-item>summary .fj-help-svg{color:var(--muted)}.fj-help-item>summary b{font-size:14px}.fj-help-chevron{color:var(--muted);font-size:18px;transition:transform .15s}.fj-help-item[open] .fj-help-chevron{transform:rotate(90deg)}.fj-help-body{padding:0 14px 14px 56px;color:var(--muted);font-size:12.5px;line-height:1.55}.fj-help-body p{margin:8px 0}.fj-help-body b{color:var(--text)}.fj-help-empty{padding:24px 2px;color:var(--muted);font-size:13px}.fj-help-footer{margin-top:18px;padding-top:14px;border-top:1px solid var(--line);color:var(--muted);font-size:11px;line-height:1.5}@media(max-width:760px){.fj-help{padding-left:16px;padding-right:16px}.fj-help-head{top:-20px}.fj-help-head h3{font-size:24px}.fj-help-item>summary{padding:12px}.fj-help-body{padding-left:54px}}@media(prefers-reduced-motion:reduce){.fj-help,.fj-help-chevron{transition:none!important}}`;document.head.appendChild(s)}

function markup(){return `<section id="fjHelp" class="fj-help" aria-label="Ajuda da aplicação"><header class="fj-help-head"><div><span class="kicker">AJUDA</span><h3>Como usar</h3></div><button type="button" class="fj-help-close" data-fj-help-close aria-label="Fechar">${ico(I.close)}</button></header><label class="fj-help-search">${ico(I.search)}<input id="fjHelpSearch" type="search" placeholder="Pesquisar função ou problema" autocomplete="off"></label><p class="fj-help-intro">Procura uma função ou abre uma categoria. Esta área explica o que cada módulo faz e o que verificar quando algo não funciona.</p><div class="fj-help-list">${HELP.map(([title,key,body,search],i)=>`<details class="fj-help-item" data-fj-help-search="${esc(`${title} ${search}`.toLowerCase())}" ${i===0?'open':''}><summary>${ico(I[key])}<b>${esc(title)}</b><span class="fj-help-chevron">›</span></summary><div class="fj-help-body">${body}</div></details>`).join('')}</div><div id="fjHelpEmpty" class="fj-help-empty" hidden>Nenhuma ajuda encontrada para essa pesquisa.</div><footer class="fj-help-footer">Para estado técnico da instalação, versão, armazenamento e Service Worker, abre <b>Mais → Sobre</b>.</footer></section>`}

function filter(){const q=($('#fjHelpSearch')?.value||'').trim().toLowerCase();let visible=0;$$('#fjHelp [data-fj-help-search]').forEach(item=>{const show=!q||item.dataset.fjHelpSearch.includes(q);item.hidden=!show;if(show){visible++;if(q)item.open=true}});const empty=$('#fjHelpEmpty');if(empty)empty.hidden=visible!==0}
function openHelp(){injectStyle();const sheet=$('#appHub .hub-sheet');if(!sheet)return;$('#hubHelp')?.remove();$('#hubAbout')?.remove();$('#fjHelp')?.remove();sheet.insertAdjacentHTML('beforeend',markup());const p=$('#fjHelp');p.querySelector('[data-fj-help-close]').onclick=()=>p.remove();p.querySelector('#fjHelpSearch').oninput=filter;requestAnimationFrame(()=>p.classList.add('open'))}

document.addEventListener('click',e=>{const t=e.target.closest?.('[data-hub-action="help"]');if(!t)return;e.preventDefault();e.stopImmediatePropagation();openHelp()},true);
window.FocoHelp=Object.freeze({open:openHelp,topics:HELP.length});
