const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fi=name=>`<i class="fi fi-rr-${name}" aria-hidden="true"></i>`;

const HELP=[
  {title:'Primeiros passos',search:'começar início hoje menu entrar instalar',body:'Usa Hoje como centro da aplicação. Inicia a jornada quando começares a trabalhar. Atividades, Planeamento, Histórico, Estatísticas, Escala, Moovit e dados ficam acessíveis pela navegação e pelo menu Mais.'},
  {title:'Jornada de trabalho',search:'jornada entrar terminar sair editar reabrir eliminar',body:'Entrar inicia a jornada. Terminar jornada encerra o registo atual. Se existir pausa ou atividade em curso, conclui primeiro esse estado. No Histórico podes editar, reabrir ou eliminar jornadas.'},
  {title:'Pausas e descanso',search:'pausa descanso ecrã intervalo regressar duração',body:'Pausa usa a duração de pausa de ecrã; Descanso usa a pausa principal. O início é manual. Quando terminares, usa Regressar. As durações são configuradas em Mais → Definições.'},
  {title:'Atividades',search:'atividade tarefa prioridade categoria subtarefa prazo recorrência etiqueta criar editar concluir',body:'Cria atividades com prioridade, categoria, descrição, prazo, recorrência, etiquetas e subtarefas. Podes iniciar, pausar, concluir, cancelar, duplicar ou mover para amanhã.'},
  {title:'Planeamento',search:'planeamento organização prioridade hoje atrasadas próximas atividades',body:'O ecrã Planeamento reúne o estado da jornada, atividades abertas, tarefas para hoje, atrasadas e as próximas prioridades. Também dá acesso rápido a Atividades, Supershift, Histórico e Hoje.'},
  {title:'Café',search:'café cafe preço vending gasto sogenave',body:'O botão + Café regista uma unidade pelo preço configurado. Quantidade e gasto aparecem nas métricas e estatísticas. O preço padrão pode ser alterado em Mais → Definições.'},
  {title:'Histórico',search:'histórico data timeline jornada eliminar editar',body:'Seleciona uma data para consultar a linha temporal e as jornadas. Podes editar horários, reabrir uma jornada concluída ou eliminar definitivamente uma jornada e os registos diretamente associados.'},
  {title:'Estatísticas',search:'estatísticas gráfico horas efetivo ano mês semana',body:'Consulta 7 dias, 30 dias ou o ano. São apresentados trabalho efetivo, jornadas registadas, atividades concluídas e café.'},
  {title:'Supershift / Escala',search:'supershift escala calendário turno rotação relatório salário copiar férias baixa falta',body:'A Escala inclui calendário, turnos, trabalhos, rotações e relatórios. No telemóvel toca num dia para editar o turno. Podes copiar para amanhã ou para a semana seguinte, aplicar férias/falta/baixa por intervalo, exportar ICS e imprimir/PDF.'},
  {title:'Moovit e transportes',search:'moovit transportes casa trabalho rota localização perto',body:'Em Mais → Moovit configura Casa e Trabalho e usa Planear com Moovit. Perto de mim abre transportes próximos. A abertura externa depende do Moovit e das permissões disponíveis no dispositivo.'},
  {title:'Notificações',search:'notificação alerta permissão iphone testar pausa',body:'Ativa as notificações em Mais → Definições e usa Testar notificação. No iPhone, notificações de sistema dependem das permissões concedidas à PWA/Safari e das definições do sistema.'},
  {title:'Dados e persistência',search:'dados guardar persistência recuperar fechar abrir supershift atividades',body:'A aplicação guarda o estado localmente e mantém uma camada de recuperação, incluindo um espelho em IndexedDB. Atividades, jornadas e Supershift devem continuar após fechar/reabrir. Limpar manualmente os dados do site pode removê-los; mantém backups quando forem importantes.'},
  {title:'Backup e diagnóstico',search:'backup exportar importar verificar dados diagnóstico restaurar',body:'Exportar backup cria uma cópia dos dados. Importar restaura uma cópia compatível após confirmação. Verificar dados executa uma análise de integridade. Usa um backup antes de trocar de dispositivo ou limpar o armazenamento.'},
  {title:'Instalar aplicação',search:'instalar aplicação iphone android pwa ecrã principal safari',body:'Abre Mais → Instalar aplicação. No iPhone usa Safari → Partilhar → Adicionar ao ecrã principal → Adicionar. Em browsers compatíveis, a aplicação apresenta o prompt nativo Instalar agora.'},
  {title:'Atualizações',search:'atualização versão cache service worker pwa',body:'Em Mais → Atualizações verifica se existe uma nova versão. Quando uma atualização estiver pronta, usa Atualizar agora. Se continuares a ver uma interface antiga, fecha completamente a PWA/Safari e abre novamente.'},
  {title:'Se algo não funcionar',search:'erro problema não funciona diagnóstico ajuda resolver cache botão',body:'Primeiro abre Mais → Backup e diagnóstico → Verificar dados. Depois confirma Mais → Sobre para versão, rede e Service Worker. Para um visual antigo, verifica Atualizações e reabre a PWA. Para funções externas, confirma permissões e aplicação correspondente.'}
];

function ensureStyle(){
  if($('#fjHelpStyle'))return;
  const style=document.createElement('style');style.id='fjHelpStyle';style.textContent=`
  .fj-help{position:absolute;inset:0;z-index:12;background:var(--bg);overflow:auto;-webkit-overflow-scrolling:touch;padding:max(18px,env(safe-area-inset-top)) 18px max(28px,env(safe-area-inset-bottom))}
  .fj-help-head{position:sticky;top:-18px;z-index:2;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:18px 0 12px;background:color-mix(in srgb,var(--bg) 95%,transparent);backdrop-filter:blur(18px);border-bottom:1px solid var(--line)}
  .fj-help-head h3{margin:2px 0;font-size:25px}.fj-help-close{display:grid;place-items:center;width:42px;height:42px;border:1px solid var(--line);border-radius:10px;background:var(--surface2);color:var(--text);font-size:18px}
  .fj-help-search{display:flex;align-items:center;gap:9px;margin:14px 0;padding:0 13px;height:46px;border:1px solid var(--line);border-radius:10px;background:var(--surface2)}
  .fj-help-search>.fi{color:var(--muted);font-size:17px}.fj-help-search input{width:100%;border:0!important;outline:0;background:transparent!important;color:var(--text)!important;font-size:15px!important;padding:0!important;min-height:0!important}
  .fj-help-intro{margin:0 0 14px;color:var(--muted);font-size:13px;line-height:1.5}.fj-help-list{display:grid;gap:8px}
  .fj-help-item{border:1px solid var(--line);border-radius:12px;background:var(--surface);overflow:hidden}.fj-help-item summary{list-style:none;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px;cursor:pointer}.fj-help-item summary::-webkit-details-marker{display:none}.fj-help-item summary b{font-size:14px}.fj-help-item summary .fi{color:var(--muted);font-size:16px;transition:transform .15s}.fj-help-item[open] summary .fi{transform:rotate(90deg)}
  .fj-help-body{padding:0 14px 15px;color:var(--muted);font-size:13px;line-height:1.58}.fj-help-empty{padding:24px 4px;color:var(--muted);font-size:13px}.fj-help-footer{margin-top:17px;padding-top:14px;border-top:1px solid var(--line);color:var(--muted);font-size:11px;line-height:1.5}
  @media(prefers-reduced-motion:reduce){.fj-help-item summary .fi{transition:none}}
  `;document.head.appendChild(style);
}

function markup(){return `<section id="fjHelp" class="fj-help" aria-label="Ajuda da aplicação"><header class="fj-help-head"><div><span class="kicker">AJUDA</span><h3>Foco & Jornada</h3></div><button type="button" class="fj-help-close" data-fj-help-close aria-label="Fechar">${fi('cross')}</button></header><label class="fj-help-search">${fi('search')}<input id="fjHelpSearch" type="search" placeholder="Pesquisar função ou problema" autocomplete="off" aria-label="Pesquisar na ajuda"></label><p class="fj-help-intro">Referência rápida das funções atuais da aplicação. Pesquisa um termo ou abre uma categoria.</p><div class="fj-help-list">${HELP.map((item,i)=>`<details class="fj-help-item" data-fj-help-search="${esc(`${item.title} ${item.search} ${item.body}`.toLowerCase())}" ${i===0?'open':''}><summary><b>${esc(item.title)}</b>${fi('angle-small-right')}</summary><div class="fj-help-body">${esc(item.body)}</div></details>`).join('')}</div><div id="fjHelpEmpty" class="fj-help-empty" hidden>Nenhuma ajuda encontrada.</div><footer class="fj-help-footer">Para diagnóstico técnico, abre Mais → Sobre ou Mais → Backup e diagnóstico.</footer></section>`}

function filter(){const q=($('#fjHelpSearch')?.value||'').trim().toLowerCase();let visible=0;$$('#fjHelp [data-fj-help-search]').forEach(item=>{const show=!q||item.dataset.fjHelpSearch.includes(q);item.hidden=!show;if(show){visible++;if(q)item.open=true}});const empty=$('#fjHelpEmpty');if(empty)empty.hidden=visible!==0}
function closeHelp(){$('#fjHelp')?.remove()}
function openHelp(){ensureStyle();const sheet=$('#appHub .hub-sheet');if(!sheet)return;$('#hubHelp')?.remove();$('#hubAbout')?.remove();closeHelp();sheet.insertAdjacentHTML('beforeend',markup());const root=$('#fjHelp');root.querySelector('[data-fj-help-close]').onclick=closeHelp;root.querySelector('#fjHelpSearch').oninput=filter}

document.addEventListener('click',e=>{const button=e.target.closest?.('[data-hub-action="help"]');if(!button)return;e.preventDefault();e.stopImmediatePropagation();openHelp()},true);
window.FocoHelp=Object.freeze({version:'3.0.0',open:openHelp,close:closeHelp});
