(function(){
'use strict';
const VERSION='1.0.0';
const $=s=>document.querySelector(s);
let deferredPrompt=null,raf=0;
const isIos=()=>/iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const isStandalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const icon='<svg class="hub-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3v12m-4-4 4 4 4-4"/><path d="M5 19h14"/><rect x="4" y="2" width="16" height="20" rx="4" opacity=".25"/></svg>';
const chev='<svg class="hub-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 6 6 6-6 6"/></svg>';
function notify(text){window.FocoUI?.notify?.(text)}
function ensureMenuItem(){const root=$('#appHub');if(!root||root.querySelector('[data-install-app]'))return;const groups=[...root.querySelectorAll('[data-hub-category]')],group=groups.find(x=>x.querySelector('h3')?.textContent.trim()==='Dados e aplicação');if(!group)return;const list=group.querySelector('.hub-category-list');if(!list)return;const btn=document.createElement('button');btn.type='button';btn.className='hub-item';btn.dataset.installApp='1';btn.dataset.hubSearch='instalar aplicação pwa ecrã principal telemóvel iphone android';btn.innerHTML=`<span class="hub-item-icon">${icon}</span><span class="hub-item-copy"><b>${isStandalone()?'Aplicação instalada':'Instalar aplicação'}</b><small>${isStandalone()?'Aberta como aplicação no dispositivo':'Adicionar ao ecrã principal do telemóvel'}</small></span><span class="hub-item-arrow">${chev}</span>`;const update=list.querySelector('[data-hub-action="updates"]');update?.after(btn)||list.appendChild(btn);btn.onclick=e=>{e.preventDefault();e.stopPropagation();openInstall()}}
function closeInstall(){$('#fjInstall')?.remove()}
function steps(){if(isStandalone())return'<h3>Aplicação instalada</h3><ol><li>Abre-a pelo ícone Foco & Jornada no ecrã principal.</li><li>Os dados continuam guardados neste dispositivo.</li></ol>';if(isIos())return'<h3>Instalar no iPhone</h3><ol><li>Abre esta página no <b>Safari</b>.</li><li>Toca no botão <b>Partilhar</b> (quadrado com seta para cima).</li><li>Escolhe <b>Adicionar ao ecrã principal</b>.</li><li>Confirma em <b>Adicionar</b>.</li><li>Depois abre Foco & Jornada pelo novo ícone.</li></ol>';if(deferredPrompt)return'<h3>Instalação disponível</h3><ol><li>Toca em <b>Instalar agora</b>.</li><li>Confirma a instalação no aviso do browser.</li><li>Abre a aplicação pelo novo ícone.</li></ol>';return'<h3>Adicionar ao telemóvel</h3><ol><li>Abre o menu do browser.</li><li>Procura <b>Instalar aplicação</b> ou <b>Adicionar ao ecrã principal</b>.</li><li>Confirma a instalação.</li></ol>'}
async function storageState(){const api=window.FocoPersistence;if(!api?.persistentStatus)return{supported:false,persisted:false};return api.persistentStatus()}
async function openInstall(){window.FocoHub?.close?.();closeInstall();const persistent=await storageState(),root=document.createElement('section');root.id='fjInstall';root.className='fj-install-backdrop';root.innerHTML=`<div class="fj-install-sheet" role="dialog" aria-modal="true" aria-labelledby="fjInstallTitle"><header class="fj-install-head"><div><span class="kicker">APLICAÇÃO</span><h2 id="fjInstallTitle">Foco & Jornada no telemóvel</h2></div><button type="button" class="fj-install-close" data-install-close aria-label="Fechar">×</button></header><div class="fj-install-status"><div><span>Modo atual</span><b>${isStandalone()?'Aplicação instalada':'Browser'}</b></div><div><span>Dados</span><b>Gravação local + recuperação</b></div><div><span>Proteção do armazenamento</span><b id="fjPersistState">${persistent.supported?(persistent.persisted?'Ativa':'Disponível'):'Gerida pelo sistema'}</b></div></div><div class="fj-install-steps">${steps()}</div><div class="fj-install-actions">${!isStandalone()?`<button type="button" class="btn primary" id="fjInstallNow">${deferredPrompt?'Instalar agora':isIos()?'Ver passos no Safari':'Como instalar'}</button>`:''}<button type="button" class="btn" id="fjProtectData">Proteger dados</button><button type="button" class="btn" id="fjBackupNow">Criar backup</button></div><p class="fj-install-note">A aplicação é local-first. A recuperação automática protege contra gravações incompletas, mas limpar os dados do browser/dispositivo pode apagar o armazenamento local. Mantém backups quando os dados forem importantes.</p></div>`;document.body.appendChild(root);root.onclick=e=>{if(e.target===root||e.target.closest('[data-install-close]'))closeInstall()};$('#fjInstallNow')?.addEventListener('click',installNow);$('#fjProtectData').onclick=protectData;$('#fjBackupNow').onclick=()=>{window.FocoPersistence?.snapshot?.();closeInstall();setTimeout(()=>$('#exportBtn')?.click(),80)}}
async function installNow(){if(isStandalone()){notify('A aplicação já está instalada.');return}if(deferredPrompt){const prompt=deferredPrompt;deferredPrompt=null;try{await prompt.prompt();const choice=await prompt.userChoice;if(choice?.outcome==='accepted')notify('Instalação iniciada.');else notify('Instalação cancelada.')}catch{notify('O browser não conseguiu iniciar a instalação.')}closeInstall();return}if(isIos()){notify('No Safari: Partilhar → Adicionar ao ecrã principal.');return}notify('Usa o menu do browser e escolhe Instalar aplicação ou Adicionar ao ecrã principal.')}
async function protectData(){const api=window.FocoPersistence;if(!api?.requestPersistentStorage){notify('A proteção adicional é gerida pelo browser neste dispositivo.');return}const result=await api.requestPersistentStorage(),label=$('#fjPersistState');if(label)label.textContent=result.persisted?'Ativa':'Não concedida';notify(result.persisted?'Proteção de armazenamento ativada.':'O browser não concedeu proteção adicional. Os dados continuam guardados localmente.')}
function schedule(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;ensureMenuItem()})}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;schedule()});
window.addEventListener('appinstalled',()=>{deferredPrompt=null;notify('Foco & Jornada instalada.');schedule()});
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});
schedule();
window.FocoInstall=Object.freeze({version:VERSION,open:openInstall,isInstalled:isStandalone});
})();
