import * as C from './core.js';

export const RECURRENCES=['none','daily','weekly','monthly'];
const pad=n=>String(n).padStart(2,'0');
export const dayKey=v=>{const d=v instanceof Date?v:new Date(v);return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const fromKey=k=>{const[y,m,d]=String(k).split('-').map(Number);return new Date(y,m-1,d,12)};
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const endOfDay=k=>{const d=fromKey(k);d.setHours(23,59,59,999);return d.getTime()};
export const parseTags=v=>[...new Set((Array.isArray(v)?v:String(v||'').split(',')).map(x=>String(x).trim()).filter(Boolean))].slice(0,12);
export function normalizeSubtasks(v,old=[]){const prev=new Map((old||[]).map(x=>[String(x.title||'').trim().toLowerCase(),x]));const rows=(Array.isArray(v)?v:String(v||'').split(/\r?\n/)).map(x=>typeof x==='string'?x:String(x?.title||'')).map(x=>x.trim()).filter(Boolean).slice(0,30);return rows.map(title=>{const p=prev.get(title.toLowerCase());return{id:p?.id||C.uid('sub'),title,done:p?.done===true,completedAt:p?.completedAt||null}})}
export function applyActivityAdvanced(a,data={},at=Date.now()){if(!a)return null;if('plannedFor'in data)a.plannedFor=data.plannedFor||null;if('dueDate'in data)a.dueAt=data.dueDate?endOfDay(data.dueDate):null;if('recurrence'in data)a.recurrence=RECURRENCES.includes(data.recurrence)?data.recurrence:'none';if('tags'in data)a.tags=parseTags(data.tags);if('subtasks'in data)a.subtasks=normalizeSubtasks(data.subtasks,a.subtasks||[]);a.updatedAt=at;a.version=(a.version||1)+1;return a}
export function activityProgress(a){const s=a?.subtasks||[];return{done:s.filter(x=>x.done).length,total:s.length}}
export const dueDateKey=a=>Number.isFinite(a?.dueAt)?dayKey(a.dueAt):null;
export const isOverdue=(a,now=Date.now())=>!['COMPLETED','CANCELLED'].includes(a?.status)&&Number.isFinite(a?.dueAt)&&a.dueAt<now;
export function toggleSubtask(state,activityId,subtaskId,at=Date.now()){const a=state.activities?.find(x=>x.id===activityId);if(!a)return{ok:false,error:'ACTIVITY_NOT_FOUND'};const sub=(a.subtasks||[]).find(x=>x.id===subtaskId);if(!sub)return{ok:false,error:'SUBTASK_NOT_FOUND'};sub.done=!sub.done;sub.completedAt=sub.done?at:null;a.updatedAt=at;a.version=(a.version||1)+1;C.pushEvent(state,'SUBTASK_TOGGLED',sub.done?'Subtarefa concluída':'Subtarefa reaberta',sub.title,at,'Activity',a.id);C.touch(state,at);return{ok:true,value:sub}}
function nextKey(base,rec){const d=fromKey(base);if(rec==='daily')d.setDate(d.getDate()+1);else if(rec==='weekly')d.setDate(d.getDate()+7);else if(rec==='monthly')d.setMonth(d.getMonth()+1);else return null;return dayKey(d)}
function cloneActivity(src,at,title=src.title){return{...C.clone(src),id:C.uid('act'),title,status:src.plannedFor?'PLANNED':'BACKLOG',completedAt:null,createdAt:at,updatedAt:at,version:1,subtasks:(src.subtasks||[]).map(s=>({...s,id:C.uid('sub'),done:false,completedAt:null}))}}
export function duplicateActivity(state,id,at=Date.now()){const src=state.activities?.find(x=>x.id===id);if(!src)return{ok:false,error:'ACTIVITY_NOT_FOUND'};const copy=cloneActivity(src,at,`${src.title} (cópia)`);state.activities.push(copy);C.pushEvent(state,'ACTIVITY_DUPLICATED','Atividade duplicada',copy.title,at,'Activity',copy.id,{sourceId:id});C.touch(state,at);return{ok:true,value:copy}}
export function moveActivityToTomorrow(state,id,at=Date.now()){const a=state.activities?.find(x=>x.id===id);if(!a)return{ok:false,error:'ACTIVITY_NOT_FOUND'};if(['COMPLETED','CANCELLED'].includes(a.status))return{ok:false,error:'ACTIVITY_NOT_EDITABLE'};a.plannedFor=dayKey(addDays(new Date(at),1));if(a.status!=='ACTIVE')a.status='PLANNED';a.updatedAt=at;a.version=(a.version||1)+1;C.pushEvent(state,'ACTIVITY_MOVED','Atividade movida para amanhã',a.title,at,'Activity',a.id,{plannedFor:a.plannedFor});C.touch(state,at);return{ok:true,value:a}}
export function completeActivityAdvanced(state,id,at=Date.now()){const src=state.activities?.find(x=>x.id===id);if(!src)return{ok:false,error:'ACTIVITY_NOT_FOUND'};const rec=RECURRENCES.includes(src.recurrence)?src.recurrence:'none',base=src.plannedFor||dayKey(at),due=dueDateKey(src),r=C.completeActivity(state,id,at);if(!r.ok||rec==='none')return r;const next=cloneActivity(src,at);next.recurrence=rec;next.recurringFrom=src.id;next.plannedFor=nextKey(base,rec);next.status='PLANNED';next.dueAt=due?endOfDay(nextKey(due,rec)):null;state.activities.push(next);C.pushEvent(state,'ACTIVITY_RECURRED','Próxima atividade recorrente criada',`${next.title} · ${next.plannedFor}`,at,'Activity',next.id);C.touch(state,at);return{...r,nextActivity:next}}

/* Compatibilidade de leitura com dados Pomodoro antigos.
   O ciclo automático foi desativado: o novo Modo Foco gere apenas sessões FOCUS. */
export function pomodoroSettings(state){const s=state.settings||(state.settings={});return{auto:false,dailyGoal:Math.max(1,Math.min(24,Number(s.focusDailyGoal)||8))}}
export function setPomodoroSettings(state,data={},at=Date.now()){state.settings.autoPomodoro=false;if('dailyGoal'in data)state.settings.focusDailyGoal=Math.max(1,Math.min(24,Number(data.dailyGoal)||8));C.touch(state,at);return pomodoroSettings(state)}
export function focusDailyStats(state,at=Date.now()){const list=(state.focusSessions||[]).filter(x=>x.phase==='FOCUS'&&C.localDayKey(x.startedAt)===C.localDayKey(at)),completed=list.filter(x=>x.status==='COMPLETED').length,goal=pomodoroSettings(state).dailyGoal;return{completed,goal,minutes:Math.round(list.reduce((s,x)=>s+C.focusEffectiveMs(x,at),0)/C.MS.minute),goalReached:completed>=goal}}
export function focusStatsForActivity(state,id,at=Date.now()){const list=(state.focusSessions||[]).filter(x=>x.phase==='FOCUS'&&x.activityId===id);return{completed:list.filter(x=>x.status==='COMPLETED').length,minutes:Math.round(list.reduce((s,x)=>s+C.focusEffectiveMs(x,at),0)/C.MS.minute)}}
export const pomodoroPhaseLabel=p=>p==='SHORT_BREAK'?'Pausa curta':p==='LONG_BREAK'?'Pausa longa':'Foco';
export function reconcilePomodoro(state,at=Date.now()){const f=C.activeFocus(state);if(!f||f.status!=='ACTIVE'||at<f.expectedEndAt)return null;const done=C.endFocus(state,f.expectedEndAt,'COMPLETED');if(!done.ok)return done;return{ok:true,completed:done.value,next:null,transitioned:false}}
