import {commandModel,buildSearchIndex,searchItems,diagnosticSnapshot,localDayKey} from './professional-core.js';

const APP_KEY='foco-jornada-v4',FEATURE_KEY='foco-jornada-features-v2';
const $=s=>document.querySelector(s);
let raf=0,lastCommandKey='';
const read=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};
const svg=body=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const I={search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',tasks:'<rect x="3" y="4" width="18" height="16" rx="3"/><path d="m8 10 2 2 4-4M15 10h3M8 16h10"/>',focus:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4M17 3v4M3 10h18"/>',bus:'<path d="M5 17h14l1-8c.2-2-1.2-4-3.3-4H7.3C5.2 5 3.8 7 4 9Z"/><path d="M7 12h10M7 17v2M17 17v2"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',history:'<path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 4v5h5"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/>'};

function ensureSearchButton(){const top=$('.top-right');if(!top||$('#professionalSearchButton'))return;const b=document.createElement('button');b.id='professionalSearchButton';b.type='button';b.className='professional-top-search';b.setAttribute('aria-label','Pesquisa global');b.innerHTML=svg(I.search);const bell=$('#notificationBell');top.insertBefore(b,bell||top.firstChild);b.onclick=openSearch}
function ensureCommand(){const hero=$('#todayHero');if(!hero)return null;let card=$('#professionalCommandCenter');if(!card){card=document.createElement('section');card.id='professionalCommandCenter';card.className='professional-command';hero.after(card)}return card}
function openCount(app){return (app.activities||[]).filter(a=>!['COMPLETED','CANCELLED'].includes(a.status)).length}
function completedFocusToday(app){const key=localDayKey();return (app.focusSessions||[]).filter(f=>f.phase==='FOCUS'&&f.status==='COMPLETED'&&localDayKey(f.startedAt)===key).length}
function renderCommand(){const card=ensureCommand();if(!card)return;const app=read(APP_KEY),features=read(FEATURE_KEY),model=commandModel(app,features),shift=model.shift,open=openCount(app),focus=completedFocusToday(app),key=JSON.stringify([model.status,model.nextTitle,model.detail,shift?.label,shift?.start,shift?.end,open,focus]);if(key===lastCommandKey)return;lastCommandKey=key;const shiftText=shift?(shift.start&&shift.end?`${shift.start}–${shift.end}`:shift.label):'Sem turno';card.innerHTML=`<div class="professional-command-head"><div><span class="kicker">CENTRO DE COMANDO</span><h2>O que precisa da tua atenção</h2></div><button type="button" class="professional-search-trigger" data-pro-action="search" aria-label="Pesquisar">${svg(I.search)}</button></div><div class="professional-command-grid"><div class="professional-next"><div class="professional-next-top"><span class="professional-status ${model.tone}">${model.status}</span><small>${open} atividade${open===1?'':'s'} aberta${open===1?'':'s'}</small></div><b>${escapeHtml(model.nextTitle)}</b><small>${escapeHtml(model.detail)}</small><button type="button" data-pro-action="next">${escapeHtml(model.nextTitle)}</button></div><div class="professional-shift"><div><small>Turno de hoje</small><strong>${escapeHtml(shift?.label||'Sem turno atribuído')}</strong></div><time>${escapeHtml(shiftText)}</time><small>${focus} sessão${focus===1?'':'ões'} de foco concluída${focus===1?'':'s'} hoje</small></div></div><div class="professional-shortcuts"><button data-pro-action="activities">${svg(I.tasks)}<span>Atividades</span></button><button data-pro-action="focus">${svg(I.focus)}<span>Foco</span></button><button data-pro-action="shift">${svg(I.calendar)}<span>Escala</span></button><button data-pro-action="moovit">${svg(I.bus)}<span>Transportes</span></button></div>`;card.onclick=handleAction}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function navigate(view){const b=$(`.bottom-nav [data-nav="${view}"]`)||$(`.side-nav [data-nav="${view}"]`);b?.click()}
function openHubAction(action){window.FocoHub?.open?.();setTimeout(()=>document.querySelector(`#appHub [data-hub-action="${action}"]`)?.click(),80)}
function runAction(action){const app=read(APP_KEY),features=read(FEATURE_KEY),model=commandModel(app,features);if(action==='search')return openSearch();if(action==='activities')return navigate('activities');if(action==='focus')return navigate('focus');if(action==='shift')return window.FocoHub?.openSupershift?.()||window.FocoShiftPlanner?.open?.();if(action==='moovit')return openHubAction('moovit');if(action==='next'){if(model.nextTitle==='Iniciar jornada'){navigate('today');setTimeout(()=>document.querySelector('[data-action="startWork"]')?.click(),80);return}return navigate(model.nextAction||'today')}}
function handleAction(e){const action=e.target.closest('[data-pro-action]')?.dataset.proAction;if(action)runAction(action)}

function ensureSearchOverlay(){let overlay=$('#professionalSearch');if(overlay)return overlay;overlay=document.createElement('section');overlay.id='professionalSearch';overlay.className='professional-overlay';overlay.hidden=true;overlay.innerHTML=`<div class="professional-sheet"><header class="professional-sheet-head"><div class="professional-search-row"><label>${svg(I.search)}<input id="professionalSearchInput" type="search" placeholder="Pesquisar na aplicação" autocomplete="off" aria-label="Pesquisa global"></label><button class="professional-close" data-pro-close aria-label="Fechar">×</button></div></header><div id="professionalResults" class="professional-results"></div></div>`;document.body.appendChild(overlay);overlay.addEventListener('click',e=>{if(e.target===overlay||e.target.closest('[data-pro-close]'))closeSearch();const row=e.target.closest('[data-search-action]');if(row){closeSearch();dispatchSearchAction(row.dataset.searchAction)}});$('#professionalSearchInput').addEventListener('input',renderSearchResults);return overlay}
function iconFor(item){if(item.category==='Atividades')return I.tasks;if(item.category==='Turnos'||item.id==='shifts')return I.calendar;if(item.id==='focus')return I.focus;if(item.id==='moovit')return I.bus;if(item.id==='notifications')return I.bell;if(item.id==='settings'||item.id==='backup'||item.id==='updates')return I.settings;if(item.id==='history')return I.history;return I.info}
function renderSearchResults(){const app=read(APP_KEY),features=read(FEATURE_KEY),q=$('#professionalSearchInput')?.value||'',items=searchItems(buildSearchIndex(app,features),q,14),host=$('#professionalResults');if(!host)return;host.innerHTML=items.length?items.map(item=>`<button type="button" class="professional-result" data-search-action="${escapeHtml(item.action)}"><span class="professional-result-icon">${svg(iconFor(item))}</span><span><b>${escapeHtml(item.title)}</b><small>${escapeHtml(item.subtitle)}</small></span><span class="professional-result-category">${escapeHtml(item.category)}</span></button>`).join(''):`<div class="professional-empty">Nenhum resultado encontrado.</div>`}
function openSearch(){const overlay=ensureSearchOverlay();overlay.hidden=false;renderSearchResults();setTimeout(()=>$('#professionalSearchInput')?.focus(),50)}
function closeSearch(){const o=$('#professionalSearch');if(o)o.hidden=true}
function dispatchSearchAction(action){if(action.startsWith('nav:'))return navigate(action.slice(4));if(action==='shift')return runAction('shift');if(action==='moovit')return runAction('moovit');if(action==='notifications')return window.FocoUI?.toggleNotifications?.(true);if(action==='updates')return openHubAction('updates');if(action==='help')return openHubAction('help');if(action==='more:settings')return openHubAction('settings');if(action==='more:backup')return openHubAction('backup');if(action==='more:about')return openDiagnostics()}

function storageBytes(){let total=0;try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';total+=new Blob([k,localStorage.getItem(k)||'']).size}}catch{}return total}
function formatBytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(2)} MB`}
async function openDiagnostics(){closeSearch();let overlay=$('#professionalDiagnostics');if(!overlay){overlay=document.createElement('section');overlay.id='professionalDiagnostics';overlay.className='professional-overlay';overlay.hidden=true;document.body.appendChild(overlay)}const app=read(APP_KEY),features=read(FEATURE_KEY);let sw='inativo';try{const reg=await navigator.serviceWorker?.getRegistration?.();sw=reg?(reg.waiting?'atualização pronta':reg.active?'ativo':'a instalar'):'não registado'}catch{}const notif='Notification'in window?Notification.permission:'indisponível',standalone=window.matchMedia?.('(display-mode: standalone)')?.matches||navigator.standalone===true,s=diagnosticSnapshot(app,features,{online:navigator.onLine,standalone,serviceWorker:sw,notifications:notif,storageBytes:storageBytes()});overlay.innerHTML=`<div class="professional-sheet"><section class="professional-diagnostic"><div class="professional-command-head"><div><span class="kicker">ESTADO DA APLICAÇÃO</span><h2>Diagnóstico</h2></div><button class="professional-close" data-diagnostic-close>×</button></div><p>Informação local para confirmar se a PWA e os módulos principais estão disponíveis.</p><div class="professional-diagnostic-grid"><div><small>Ligação</small><b>${s.online?'Online':'Offline'}</b></div><div><small>Modo</small><b>${s.standalone?'PWA instalada':'Browser'}</b></div><div><small>Service Worker</small><b>${escapeHtml(s.serviceWorker)}</b></div><div><small>Notificações</small><b>${escapeHtml(s.notifications)}</b></div><div><small>Dados locais</small><b>${formatBytes(s.storageBytes)}</b></div><div><small>Jornadas</small><b>${s.counts.jornadas}</b></div><div><small>Atividades</small><b>${s.counts.atividades}</b></div><div><small>Foco</small><b>${s.counts.foco}</b></div><div><small>Turnos</small><b>${s.counts.turnos}</b></div><div><small>Modelos</small><b>${s.counts.modelos}</b></div></div><div class="professional-diagnostic-actions"><button data-diagnostic-copy>Copiar diagnóstico</button><button class="primary" data-diagnostic-update>Verificar atualização</button></div></section></div>`;overlay.hidden=false;overlay.onclick=e=>{if(e.target===overlay||e.target.closest('[data-diagnostic-close]'))overlay.hidden=true;if(e.target.closest('[data-diagnostic-copy]'))copyDiagnostic(s);if(e.target.closest('[data-diagnostic-update]')){overlay.hidden=true;openHubAction('updates')}}}
async function copyDiagnostic(snapshot){const text=JSON.stringify({product:'Foco & Jornada',generatedAt:new Date().toISOString(),...snapshot},null,2);try{await navigator.clipboard.writeText(text);window.FocoUI?.notify?.('Diagnóstico copiado.')}catch{window.FocoUI?.notify?.('Não foi possível copiar o diagnóstico.')}}
function ensureDiagnosticLink(){const about=$('#appVersion')?.closest('.panel');if(!about||about.querySelector('[data-open-professional-diagnostic]'))return;const b=document.createElement('button');b.type='button';b.className='btn';b.dataset.openProfessionalDiagnostic='1';b.textContent='Estado da aplicação';b.onclick=openDiagnostics;about.appendChild(b)}
function schedule(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;ensureSearchButton();renderCommand();ensureDiagnosticLink()})}
window.addEventListener('storage',schedule);window.addEventListener('online',schedule);window.addEventListener('offline',schedule);window.addEventListener('foco-shift-planner-change',schedule);document.addEventListener('click',()=>setTimeout(schedule,0));document.addEventListener('change',()=>setTimeout(schedule,0));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')closeSearch()});new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();window.FocoProfessional=Object.freeze({version:'1.0.0',openSearch,openDiagnostics,refresh:schedule});
