import * as C from './core.js';
import {summarizeDay,localDayKey} from './features-core.js';
import {normalizePlanner,exportPlannerIcs} from './shift-planner-core.js';

const APP_KEY='foco-jornada-v4',FEATURE_KEY='foco-jornada-features-v2',RESTORE_VIEW_KEY='foco-jornada-runtime-view-v1',LAST_SHIFT_MONTH_KEY='foco-jornada-shift-print-month-v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let raf=0,updateReloadArmed=false;

function ensureCss(){if($('#runtimeFixesCss'))return;const l=document.createElement('link');l.id='runtimeFixesCss';l.rel='stylesheet';l.href='./runtime-fixes.css';document.head.appendChild(l)}
function ensureFunctionalStyles(){if($('#runtimeFunctionalStyles'))return;const s=document.createElement('style');s.id='runtimeFunctionalStyles';s.textContent=`.runtime-notification-tools{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 14px;margin:8px 0 4px;border:1px solid var(--line);border-radius:16px;background:var(--surface2)}.runtime-notification-tools b,.runtime-notification-tools small{display:block}.runtime-notification-tools small{margin-top:4px;color:var(--muted);font-size:12px}.sp-day{touch-action:manipulation!important}@media(max-width:520px){.runtime-notification-tools{align-items:stretch;flex-direction:column}.runtime-notification-tools .btn{width:100%}}@page{size:A4 portrait;margin:12mm}@media print{body.sp-print-a4{background:#fff!important;color:#111!important}body.sp-print-a4>*:not(#shiftPlanner){display:none!important}body.sp-print-a4 #shiftPlanner{display:block!important;position:static!important;inset:auto!important;background:#fff!important;color:#111!important;overflow:visible!important}body.sp-print-a4 #shiftPlanner .sp-shell{width:100%!important;max-width:none!important;min-height:0!important;background:#fff!important;color:#111!important}body.sp-print-a4 #shiftPlanner .sp-top-actions,body.sp-print-a4 #shiftPlanner .sp-bottom,body.sp-print-a4 #shiftPlanner .sp-fab,body.sp-print-a4 #spModal{display:none!important}body.sp-print-a4 #shiftPlanner .sp-main{padding:8mm 0 0!important;overflow:visible!important}body.sp-print-a4 #shiftPlanner .sp-calendar-card,body.sp-print-a4 #shiftPlanner .sp-report-card,body.sp-print-a4 #shiftPlanner .sp-list-card{background:#fff!important;color:#111!important;border:1px solid #bbb!important;box-shadow:none!important;break-inside:avoid}}`;document.head.appendChild(s)}
function readApp(){try{return C.migrateState(JSON.parse(localStorage.getItem(APP_KEY)||'null'))}catch{return null}}
function writeApp(v){if(!v)return;v.updatedAt=Date.now();localStorage.setItem(APP_KEY,JSON.stringify(v))}
function readFeature(){try{return JSON.parse(localStorage.getItem(FEATURE_KEY)||'{}')||{}}catch{return{}}}
function writeFeature(v){localStorage.setItem(FEATURE_KEY,JSON.stringify(v||{}))}
function readPlanner(){return normalizePlanner(readFeature().shiftPlanner||{})}
function notify(text,label='',fn=null){window.FocoUI?.notify?.(text,label,fn)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(c){return new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format((Number(c)||0)/100)}
function fmtDur(ms){ms=Math.max(0,Number(ms)||0);const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return h?`${h}h ${String(m).padStart(2,'0')}m`:`${m} min`}
function reloadTo(view){sessionStorage.setItem(RESTORE_VIEW_KEY,view);location.reload()}
function restoreView(){const v=sessionStorage.getItem(RESTORE_VIEW_KEY);if(!v)return;sessionStorage.removeItem(RESTORE_VIEW_KEY);setTimeout(()=>document.querySelector(`.bottom-nav [data-nav="${v}"]`)?.click()||document.querySelector(`.side-nav [data-nav="${v}"]`)?.click(),120)}
function modal(html){$('#runtimeDialog')?.remove();const root=document.createElement('div');root.id='runtimeDialog';root.className='runtime-dialog-backdrop';root.innerHTML=`<div class="runtime-dialog" role="dialog" aria-modal="true">${html}</div>`;document.body.appendChild(root);root.addEventListener('click',e=>{if(e.target===root||e.target.closest('[data-runtime-close]'))root.remove()});return root}
function confirmAction(title,body,label,onConfirm,danger=false){const r=modal(`<header><h2>${esc(title)}</h2><button type="button" data-runtime-close>×</button></header><p>${esc(body)}</p><div class="runtime-dialog-actions"><button type="button" class="btn" data-runtime-close>Cancelar</button><button type="button" class="btn ${danger?'danger-fill':'primary'}" id="runtimeConfirm">${esc(label)}</button></div>`);r.querySelector('#runtimeConfirm').onclick=()=>{r.remove();onConfirm()}}

function notificationPermissionText(){if(!('Notification'in window))return'Alertas internos disponíveis; notificações do sistema não suportadas neste browser.';return Notification.permission==='granted'?'Notificações do sistema autorizadas.':Notification.permission==='denied'?'Notificações do sistema bloqueadas nas definições do dispositivo.':'Permissão do sistema ainda não concedida.'}
function ensureNotificationTools(){const input=$('#setNotifications');if(!input)return;let tools=$('#runtimeNotificationTools');if(!tools){tools=document.createElement('div');tools.id='runtimeNotificationTools';tools.className='runtime-notification-tools';tools.innerHTML='<div><b>Estado das notificações</b><small id="runtimeNotificationStatus"></small></div><button type="button" class="btn" data-runtime-test-notification>Testar notificação</button>';input.closest('label')?.after(tools)}const status=$('#runtimeNotificationStatus'),text=notificationPermissionText();if(status&&status.textContent!==text)status.textContent=text}

function exportFullBackup(){const state=readApp();if(!state)return notify('Não foi possível criar o backup.');const payload={product:'Foco & Jornada',appVersion:state.appVersion||'4.2.x',schemaVersion:C.SCHEMA_VERSION,exportedAt:new Date().toISOString(),state,features:readFeature()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`foco-jornada-backup-${localDayKey(Date.now())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200);notify('Backup completo criado.')}
async function handleImportFile(file){if(!file)return;try{const obj=JSON.parse(await file.text()),incoming=C.migrateState(obj.state||obj),issues=C.validateState(incoming,Date.now());confirmAction('Importar backup?',`Serão restauradas ${incoming.workSessions.length} jornadas, ${incoming.activities.length} atividades e ${incoming.coffeeEntries.length} cafés.${issues.length?` Diagnóstico: ${issues.length} aviso(s).`:''}`,'Restaurar backup',()=>{writeApp(incoming);if(obj.features&&typeof obj.features==='object')writeFeature(obj.features);notify('Backup restaurado. A aplicação vai recarregar.');setTimeout(()=>reloadTo('today'),200)})}catch{notify('O ficheiro selecionado não é um backup válido da Foco & Jornada.')}finally{if($('#importInput'))$('#importInput').value=''}}
function resetAllData(){confirmAction('Apagar todos os dados?','Serão eliminadas jornadas, atividades, foco, café, escala, transportes, notificações e preferências locais deste dispositivo.','Apagar tudo',()=>{for(const key of Object.keys(localStorage))if(key.startsWith('foco-jornada-'))localStorage.removeItem(key);const fresh=C.createInitialState();fresh.settings.onboardingDone=true;const coffee=fresh.settings.coffeeTypes.find(x=>x.id===fresh.settings.defaultCoffeeTypeId);if(coffee){coffee.name='Café vending Sogenave';coffee.priceCents=40}writeApp(fresh);notify('Dados locais apagados.');setTimeout(()=>location.reload(),220)},true)}

function dailySnapshot(){const state=readApp();if(!state)return null;const key=localDayKey(Date.now()),summary=summarizeDay(state,key,Date.now());return{key,closedAt:Date.now(),...summary}}
function closeDailySummary(){const snap=dailySnapshot();if(!snap)return notify('Não foi possível fechar o resumo.');const f=readFeature();f.closedDays=Array.isArray(f.closedDays)?f.closedDays:[];f.dailyClosures=f.dailyClosures&&typeof f.dailyClosures==='object'?f.dailyClosures:{};if(!f.closedDays.includes(snap.key))f.closedDays.push(snap.key);f.dailyClosures[snap.key]=snap;writeFeature(f);renderClosedSummary(true);notify('Dia fechado. O resumo foi arquivado neste dispositivo.')}
function reopenDailySummary(){const key=localDayKey(Date.now()),f=readFeature();f.closedDays=(Array.isArray(f.closedDays)?f.closedDays:[]).filter(x=>x!==key);if(f.dailyClosures)delete f.dailyClosures[key];writeFeature(f);reloadTo('today')}
function renderClosedSummary(force=false){const card=$('#dailySummaryCard');if(!card)return;const key=localDayKey(Date.now()),f=readFeature(),closed=Array.isArray(f.closedDays)&&f.closedDays.includes(key);if(!force&&!closed)return;if(card.dataset.runtimeClosed==='1')return;const snap=f.dailyClosures?.[key];card.dataset.runtimeClosed='1';card.innerHTML=`<div class="runtime-summary-closed"><div><span class="kicker">FECHO DO DIA</span><b>Dia fechado${snap?.closedAt?` às ${new Intl.DateTimeFormat('pt-PT',{hour:'2-digit',minute:'2-digit'}).format(new Date(snap.closedAt))}`:''}</b><small>${snap?`${fmtDur(snap.effectiveWorkMs)} efetivos · ${fmtDur(snap.focusMs)} foco · ${snap.completedActivities} atividades · ${snap.coffeeCount} cafés (${money(snap.coffeeSpendCents)})`:'O resumo ficou arquivado localmente.'}</small></div><button type="button" class="btn" data-runtime-reopen-summary>Reabrir dia</button></div>`}

const MONTHS_PT=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
function rememberShiftMonth(){const title=$('#shiftPlanner .sp-top h1')?.textContent?.trim().toLowerCase()||'',m=MONTHS_PT.findIndex(x=>title.startsWith(x)),year=Number(title.match(/\b(20\d{2})\b/)?.[1]);if(m>=0&&Number.isFinite(year))sessionStorage.setItem(LAST_SHIFT_MONTH_KEY,`${year}-${String(m+1).padStart(2,'0')}`)}
function plannerMonth(){const saved=sessionStorage.getItem(LAST_SHIFT_MONTH_KEY);if(saved&&/^20\d{2}-\d{2}$/.test(saved)){const[y,m]=saved.split('-').map(Number);return new Date(y,m-1,1)}return new Date()}
async function sharePlannerIcs(){const p=readPlanner(),month=plannerMonth(),start=new Date(month.getFullYear(),month.getMonth(),1),end=new Date(month.getFullYear(),month.getMonth()+1,0),ics=exportPlannerIcs(p,start,end),filename=`escala-${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}.ics`,file=new File([ics],filename,{type:'text/calendar;charset=utf-8'});try{if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Escala de trabalho',files:[file]});notify('Calendário partilhado.');return}}catch(e){if(e?.name==='AbortError')return}const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);notify('Ficheiro .ics criado.')}
function printPlannerA4(){document.body.classList.add('sp-print-a4');const cleanup=()=>document.body.classList.remove('sp-print-a4');window.addEventListener('afterprint',cleanup,{once:true});try{window.print()}finally{setTimeout(cleanup,1200)}}
function activateWaiting(reg){if(!reg?.waiting)return notify('Ainda não existe uma atualização pronta para instalar.');if(!updateReloadArmed){updateReloadArmed=true;navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true})}reg.waiting.postMessage({type:'SKIP_WAITING'});notify('A atualizar a aplicação…')}
async function checkForAppUpdate(){window.FocoHub?.close?.();if(!('serviceWorker'in navigator))return notify('Atualizações automáticas não estão disponíveis neste browser.');try{const reg=await navigator.serviceWorker.getRegistration();if(!reg)return notify('O modo PWA ainda não está ativo.');await reg.update();if(reg.waiting)notify('Nova versão pronta.','Atualizar agora',()=>activateWaiting(reg));else notify('A aplicação já está na versão mais recente disponível.')}catch{notify('Não foi possível verificar atualizações agora.')}}
function fixSupershiftUi(){const kicker=$('#shiftPlanner .sp-kicker');if(kicker&&kicker.textContent!=='SUPERSHIFT')kicker.textContent='SUPERSHIFT';const next=$('#shiftPlanner [data-sp-action="next-month"]');if(next&&!next.dataset.runtimeArrow){next.dataset.runtimeArrow='1';next.innerHTML='<svg class="sp-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>'}rememberShiftMonth()}
function bindImport(){const input=$('#importInput');if(!input||input.dataset.runtimeImport==='1')return;input.dataset.runtimeImport='1';input.addEventListener('change',e=>{e.preventDefault();e.stopImmediatePropagation();handleImportFile(e.target.files?.[0])},true)}
function auditButtons(){$$('button[data-nav],button[data-filter],button[data-period],button[data-action],button[data-hub-action],button[data-sp-action],button[data-sp-tab],button[data-sp-day]').forEach(b=>b.dataset.runtimeAudited='1')}
function enhance(){fixSupershiftUi();renderClosedSummary();ensureNotificationTools();bindImport();auditButtons()}
function schedule(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;enhance()})}

document.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;if(t.id==='exportBtn'){e.preventDefault();e.stopImmediatePropagation();exportFullBackup();return}if(t.id==='resetBtn'){e.preventDefault();e.stopImmediatePropagation();resetAllData();return}if(t.id==='closeTodayBtn'){e.preventDefault();e.stopImmediatePropagation();closeDailySummary();return}if(t.matches('[data-runtime-reopen-summary]')){e.preventDefault();e.stopImmediatePropagation();reopenDailySummary();return}if(t.matches('[data-sp-action="export-ics"]')){e.preventDefault();e.stopImmediatePropagation();sharePlannerIcs();return}if(t.matches('[data-sp-action="print"]')){e.preventDefault();e.stopImmediatePropagation();printPlannerA4();return}if(t.matches('[data-hub-action="updates"]')){e.preventDefault();e.stopImmediatePropagation();checkForAppUpdate();return}},true);
document.addEventListener('change',e=>{if(e.target?.id==='setNotifications')setTimeout(ensureNotificationTools,0)},true);
ensureCss();ensureFunctionalStyles();restoreView();schedule();
const runtimeObserver=new MutationObserver(mutations=>{for(const mutation of mutations){if([...mutation.addedNodes].some(node=>node.nodeType===1)){schedule();break}}});
runtimeObserver.observe(document.body,{childList:true,subtree:true});
window.FocoRuntimeFixes=Object.freeze({version:'1.3.0',enhance,audit:auditButtons,checkUpdate:checkForAppUpdate,printA4:printPlannerA4,exportIcs:sharePlannerIcs});
