import {normalizePlanner,monthReport} from './shift-planner-core.js';

const FEATURE_KEY='foco-jornada-features-v2';
const $=s=>document.querySelector(s);
let raf=0;

function readFeature(){try{return JSON.parse(localStorage.getItem(FEATURE_KEY)||'{}')||{}}catch{return{}}}
function readPlanner(){return normalizePlanner(readFeature().shiftPlanner||{})}
function writePlanner(planner){const f=readFeature();f.shiftPlanner=planner;localStorage.setItem(FEATURE_KEY,JSON.stringify(f));window.dispatchEvent(new CustomEvent('foco-shift-planner-change'))}
function notify(text){window.FocoUI?.notify?.(text)}
const money=c=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format((Number(c)||0)/100);
const number=v=>String(v??'').trim();

function ensureCss(){if($('#shiftReportsCss'))return;const style=document.createElement('style');style.id='shiftReportsCss';style.textContent=`
.sp-report-config{display:grid;gap:14px}.sp-report-config .sp-report-config-head b,.sp-report-config .sp-report-config-head small{display:block}.sp-report-config .sp-report-config-head b{font-size:16px}.sp-report-config .sp-report-config-head small{margin-top:4px;color:var(--muted);font-size:12px;line-height:1.4}.sp-report-config-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.sp-report-config label{display:grid;gap:6px;color:var(--muted);font-size:12px}.sp-report-config input{width:100%;min-height:46px;border:1px solid var(--line);border-radius:13px;background:var(--surface2);color:var(--text);padding:10px 12px;font-size:16px;font-variant-numeric:tabular-nums}.sp-report-config-actions{display:flex;gap:10px;flex-wrap:wrap}.sp-report-config-actions button{flex:1}.sp-report-unset{color:var(--muted)!important;font-size:16px!important;font-weight:700!important}.sp-report-hint{display:block;margin-top:5px;color:var(--muted);font-size:11px;font-weight:500;line-height:1.35}@media(max-width:520px){.sp-report-config-grid{grid-template-columns:1fr}.sp-report-config-actions{flex-direction:column}.sp-report-config-actions button{width:100%}}
`;document.head.appendChild(style)}

function migrateLegacyDefaults(){const f=readFeature(),p=normalizePlanner(f.shiftPlanner||{}),job=p.jobs.find(x=>x.isDefault)||p.jobs[0];if(!job)return;const settings=p.settings||(p.settings={});let changed=false;if(settings.reportTargetConfigured!==true&&job.targetMonthlyMinutes===217*60){job.targetMonthlyMinutes=0;changed=true}if(settings.reportRateConfigured!==true&&job.hourlyRateCents===523){job.hourlyRateCents=0;changed=true}if(settings.reportLegacyDefaultsCleaned!==true){settings.reportLegacyDefaultsCleaned=true;changed=true}if(changed){f.shiftPlanner=p;localStorage.setItem(FEATURE_KEY,JSON.stringify(f))}}

function configCard(p,job){const targetSet=p.settings?.reportTargetConfigured===true,rateSet=p.settings?.reportRateConfigured===true;const targetValue=targetSet&&job.targetMonthlyMinutes>0?(job.targetMonthlyMinutes/60).toFixed(1):'';const rateValue=rateSet?(job.hourlyRateCents/100).toFixed(2):'';return `<article class="sp-report-card sp-report-config" id="spReportConfig"><div class="sp-report-config-head"><b>Configuração do cálculo</b><small>Define apenas os valores que realmente usas. Nada é assumido automaticamente.</small></div><div class="sp-report-config-grid"><label>Horas normais por mês<input id="spInlineTargetHours" type="number" min="0" max="400" step="0.5" inputmode="decimal" placeholder="Ex.: 160" value="${targetValue}"></label><label>Salário por hora (€)<input id="spInlineHourlyRate" type="number" min="0" max="999" step="0.01" inputmode="decimal" placeholder="Ex.: 6,50" value="${rateValue}"></label></div><div class="sp-report-config-actions"><button type="button" class="sp-primary" data-report-save>Guardar valores</button><button type="button" class="sp-danger" data-report-clear>Limpar cálculos</button></div></article>`}

function patchReportValues(p,job){const stack=$('#shiftPlanner .sp-report-stack');if(!stack)return;const report=monthReport(p,new Date());const targetSet=p.settings?.reportTargetConfigured===true,rateSet=p.settings?.reportRateConfigured===true;const cards=[...stack.querySelectorAll('.sp-report-card')];const overtimeCard=cards.find(c=>c.querySelector('h2')?.textContent.trim()==='Horas extraordinárias');if(overtimeCard){const rows=[...overtimeCard.querySelectorAll('.sp-report-lines > div')];if(rows[0]?.querySelector('strong')){rows[0].querySelector('strong').textContent=targetSet?`${(job.targetMonthlyMinutes/60).toFixed(1).replace('.0','')}h`:'—';rows[0].querySelector('strong').classList.toggle('sp-report-unset',!targetSet)}if(rows[2]?.querySelector('strong')){rows[2].querySelector('strong').textContent=targetSet?`${report.overtimeMinutes<0?'-':''}${Math.abs(report.overtimeMinutes/60).toFixed(1).replace('.0','')}h`:'—';rows[2].querySelector('strong').classList.toggle('sp-report-unset',!targetSet);if(!targetSet&&!rows[2].querySelector('.sp-report-hint'))rows[2].querySelector('b')?.insertAdjacentHTML('beforeend','<small class="sp-report-hint">Define as horas normais para calcular horas extraordinárias.</small>')}}const gainsCard=cards.find(c=>c.querySelector('h2')?.textContent.trim()==='Ganhos');if(gainsCard){const strong=gainsCard.querySelector('.sp-report-lines strong');if(strong){strong.textContent=rateSet?money(report.earningsCents):'—';strong.classList.toggle('sp-report-unset',!rateSet)}const label=gainsCard.querySelector('.sp-report-lines b');if(label&&!rateSet&&!label.querySelector('.sp-report-hint'))label.insertAdjacentHTML('beforeend','<small class="sp-report-hint">Define o salário/hora para calcular ganhos.</small>')}}
}

function enhance(){ensureCss();const plannerRoot=$('#shiftPlanner');if(!plannerRoot||plannerRoot.hidden)return;const stack=plannerRoot.querySelector('.sp-report-stack');if(!stack)return;const p=readPlanner(),job=p.jobs.find(x=>x.isDefault)||p.jobs[0];if(!job)return;if(!$('#spReportConfig'))stack.insertAdjacentHTML('afterbegin',configCard(p,job));patchReportValues(p,job)}
function schedule(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;enhance()})}

function saveConfig(){const p=readPlanner(),job=p.jobs.find(x=>x.isDefault)||p.jobs[0];if(!job)return;const targetRaw=number($('#spInlineTargetHours')?.value),rateRaw=number($('#spInlineHourlyRate')?.value);p.settings=p.settings||{};p.settings.reportTargetConfigured=targetRaw!=='';p.settings.reportRateConfigured=rateRaw!=='';job.targetMonthlyMinutes=targetRaw===''?0:Math.round(Math.max(0,Math.min(400,Number(targetRaw)||0))*60);job.hourlyRateCents=rateRaw===''?0:Math.round(Math.max(0,Math.min(999,Number(rateRaw)||0))*100);writePlanner(p);notify('Horas e salário guardados. Relatório recalculado.');window.FocoShiftPlanner?.render?.();schedule()}
function clearConfig(){const p=readPlanner(),job=p.jobs.find(x=>x.isDefault)||p.jobs[0];if(!job)return;p.settings=p.settings||{};p.settings.reportTargetConfigured=false;p.settings.reportRateConfigured=false;job.targetMonthlyMinutes=0;job.hourlyRateCents=0;writePlanner(p);notify('Cálculos de horas e ganhos limpos.');window.FocoShiftPlanner?.render?.();schedule()}

document.addEventListener('click',e=>{if(e.target.closest('[data-report-save]')){e.preventDefault();e.stopImmediatePropagation();saveConfig();return}if(e.target.closest('[data-report-clear]')){e.preventDefault();e.stopImmediatePropagation();clearConfig()}},true);

migrateLegacyDefaults();ensureCss();schedule();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('foco-shift-planner-change',schedule);window.FocoShiftReports=Object.freeze({version:'1.0.0',enhance,save:saveConfig,clear:clearConfig});
