const STORAGE_KEY='foco-jornada-v4';
const META_KEY='foco-jornada-enhancements-meta';
const VERSION='4.2.0';
const nativeSetInterval=window.setInterval.bind(window);
let appSecondLoop=null;

window.setInterval=(fn,ms,...args)=>{if(ms===1000&&!appSecondLoop){appSecondLoop=fn;return 0}return nativeSetInterval(fn,ms,...args)};
await import('./app.js');
window.setInterval=nativeSetInterval;

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const readState=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}};
const writeState=s=>localStorage.setItem(STORAGE_KEY,JSON.stringify(s));
const readMeta=()=>{try{return JSON.parse(localStorage.getItem(META_KEY)||'{}')}catch{return{}}};
const writeMeta=m=>localStorage.setItem(META_KEY,JSON.stringify(m));
const dayKey=ts=>{const d=new Date(ts);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const pad=n=>String(n).padStart(2,'0');
const fmtClock=ts=>{const d=new Date(ts);return `${pad(d.getHours())}:${pad(d.getMinutes())}`};
const fmtDuration=ms=>{ms=Math.max(0,Number(ms)||0);const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return `${pad(h)}:${pad(m)}:${pad(s)}`};
const fmtShort=ms=>{ms=Math.max(0,Number(ms)||0);const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return h?`${h}h ${pad(m)}m`:`${m} min`};
const formatBytes=bytes=>bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(2)} MB`;
const dateLabel=ts=>ts?new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(ts)):'Ainda não';
function activeContext(state){return state?.settings?.activeContextId||'work'}
function activeWork(state){return state?.workSessions?.find(x=>x.status==='ACTIVE'&&x.contextId===activeContext(state))||null}
function activeBreak(state){return state?.breakSessions?.find(x=>x.status==='ACTIVE')||null}
function activeFocus(state){return state?.focusSessions?.find(x=>x.status==='ACTIVE'||x.status==='PAUSED')||null}
function breakMsForWork(state,w,now){const end=w.endedAt??now;return (state?.breakSessions||[]).filter(b=>b.workSessionId===w.id&&b.status!=='CANCELLED').reduce((sum,b)=>sum+Math.max(0,Math.min(b.endedAt??now,end)-Math.max(b.startedAt,w.startedAt)),0)}
function focusRemaining(f,now){if(!f)return 0;const t=f.status==='PAUSED'&&f.pausedAt?f.pausedAt:now;return Math.max(0,(f.expectedEndAt??t)-t)}

function migrateCoffeeDefaults(){const state=readState();if(!state?.settings?.coffeeTypes)return false;const id=state.settings.defaultCoffeeTypeId||'espresso',coffee=state.settings.coffeeTypes.find(c=>c.id===id)||state.settings.coffeeTypes.find(c=>c.id==='espresso');if(!coffee)return false;let changed=false;if(coffee.priceCents===70){coffee.priceCents=40;changed=true}if(!coffee.name||coffee.name==='Café'){coffee.name='Café vending Sogenave';changed=true}if(changed)writeState(state);return changed}
function injectStyles(){if($('#fj-stability-style'))return;const style=document.createElement('style');style.id='fj-stability-style';style.textContent=`button{touch-action:manipulation}#historyTimeline .event{grid-template-columns:76px minmax(0,1fr) auto!important;align-items:center}.fj-history-delete{width:50px;height:50px;border-radius:15px;border:1px solid var(--line);background:var(--surface2);color:var(--danger);display:grid;place-items:center;padding:0}.fj-history-tools{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.fj-backup-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0}.fj-backup-stat{border:1px solid var(--line);background:var(--surface2);border-radius:14px;padding:12px}.fj-backup-stat small,.fj-backup-stat strong{display:block}.fj-backup-stat small{color:var(--muted);margin-bottom:5px}.fj-setting-help{font-size:12px;color:var(--muted);margin-top:-2px}.fj-toggle{display:flex!important;align-items:center;gap:10px}.fj-toggle input{width:22px!important;min-height:22px!important;margin:0}.fj-toggle span{font-size:13px}@media(max-width:560px){#historyTimeline .event{grid-template-columns:64px minmax(0,1fr) 52px!important}.fj-backup-summary{grid-template-columns:1fr}}`;document.head.appendChild(style)}
function fixVersion(){for(const id of ['#appVersion','#appVersionSide']){const el=$(id);if(el&&el.textContent!==VERSION)el.textContent=VERSION}}
function observeVersion(){const observer=new MutationObserver(()=>queueMicrotask(fixVersion));for(const id of ['#appVersion','#appVersionSide']){const el=$(id);if(el)observer.observe(el,{childList:true,characterData:true,subtree:true})}}
function enhanceSettings(){const form=$('#settingsForm');if(!form)return;if(!$('#setCoffeeName')){const price=$('#setCoffee')?.closest('label');if(price){const label=document.createElement('label');label.innerHTML='Nome do café padrão<input id="setCoffeeName" type="text" maxlength="50" placeholder="Café vending Sogenave">';price.before(label);const help=document.createElement('small');help.className='fj-setting-help';help.textContent='Máquina vending Sogenave: 0,40 € por café. O valor continua editável.';price.appendChild(help)}}if(!$('#setNotifications')){const wide=form.querySelector('.wide'),label=document.createElement('label');label.className='fj-toggle';label.innerHTML='<input id="setNotifications" type="checkbox"><span>Notificações quando foco/pausa terminar</span>';wide?.before(label)}const state=readState(),coffee=state?.settings?.coffeeTypes?.find(c=>c.id===(state.settings.defaultCoffeeTypeId||'espresso'));if($('#setCoffeeName')&&!$('#setCoffeeName').matches(':focus'))$('#setCoffeeName').value=coffee?.name||'Café vending Sogenave';if($('#setNotifications'))$('#setNotifications').checked=!!state?.settings?.notifications;if($('#setCoffee')&&!$('#setCoffee').matches(':focus')&&coffee?.priceCents!=null)$('#setCoffee').value=(coffee.priceCents/100).toFixed(2);if(form.dataset.fjStable)return;form.dataset.fjStable='1';form.addEventListener('submit',()=>{const name=$('#setCoffeeName')?.value?.trim()||'Café vending Sogenave',notifications=!!$('#setNotifications')?.checked;setTimeout(()=>{const current=readState();if(!current)return;const c=current.settings?.coffeeTypes?.find(x=>x.id===(current.settings.defaultCoffeeTypeId||'espresso'));if(c)c.name=name;current.settings.notifications=notifications;writeState(current);if(notifications&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});enhanceAll()},0)})}
function enhanceHistory(){const timeline=$('#historyTimeline');if(!timeline)return;const date=$('#historyDate')?.value||dayKey(Date.now()),state=readState();if(!state)return;const events=(state.events||[]).filter(e=>dayKey(e.occurredAt)===date).sort((a,b)=>b.occurredAt-a.occurredAt||String(b.id).localeCompare(String(a.id)));$$('#historyTimeline .event').forEach((row,i)=>{if(row.querySelector('.fj-history-delete')||!events[i])return;const eventId=events[i].id,btn=document.createElement('button');btn.type='button';btn.className='fj-history-delete';btn.textContent='⌫';btn.setAttribute('aria-label','Eliminar item da timeline');btn.title='Eliminar da timeline';btn.onclick=ev=>{ev.stopPropagation();if(!confirm('Eliminar este item da timeline? O dado principal associado será preservado.'))return;const current=readState();if(!current)return;current.events=(current.events||[]).filter(e=>e.id!==eventId);writeState(current);sessionStorage.setItem('fj-restore-view','history');sessionStorage.setItem('fj-history-date',date);location.reload()};row.appendChild(btn)});const panel=timeline.closest('.panel'),head=panel?.querySelector('.section-head');if(head&&!head.querySelector('.fj-clear-day')){const tools=document.createElement('div');tools.className='fj-history-tools';const clear=document.createElement('button');clear.type='button';clear.className='mini danger fj-clear-day';clear.textContent='Limpar dia';clear.onclick=ev=>{ev.stopPropagation();if(!confirm('Limpar todos os itens da timeline desta data? Jornadas, tempos e totais permanecem guardados.'))return;const current=readState();if(!current)return;current.events=(current.events||[]).filter(e=>dayKey(e.occurredAt)!==date);writeState(current);sessionStorage.setItem('fj-restore-view','history');sessionStorage.setItem('fj-history-date',date);location.reload()};tools.appendChild(clear);head.appendChild(tools)}}
function downloadDiagnostic(){const state=readState();if(!state)return;const issues=[];if((state.workSessions||[]).filter(x=>x.status==='ACTIVE').length>1)issues.push('Várias jornadas ativas');if((state.breakSessions||[]).filter(x=>x.status==='ACTIVE').length>1)issues.push('Várias pausas ativas');if((state.focusSessions||[]).filter(x=>['ACTIVE','PAUSED'].includes(x.status)).length>1)issues.push('Várias sessões de foco ativas');if((state.activitySegments||[]).filter(x=>x.endedAt==null).length>1)issues.push('Várias atividades ativas');const payload={product:'Foco & Jornada',uiVersion:VERSION,generatedAt:new Date().toISOString(),issues,counts:{jornadas:state.workSessions?.length||0,pausas:state.breakSessions?.length||0,atividades:state.activities?.length||0,foco:state.focusSessions?.length||0,cafes:state.coffeeEntries?.length||0,eventos:state.events?.length||0},settings:state.settings};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`foco-jornada-diagnostico-${dayKey(Date.now())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function enhanceBackup(){const heading=$$('h2').find(h=>h.textContent.trim()==='Backup e diagnóstico'),panel=heading?.closest('.panel'),buttons=panel?.querySelector('.button-row');if(!panel||!buttons)return;if(!panel.querySelector('.fj-backup-summary')){const summary=document.createElement('div');summary.className='fj-backup-summary';buttons.before(summary)}if(!panel.querySelector('.fj-download-diagnostic')){const b=document.createElement('button');b.type='button';b.className='btn fj-download-diagnostic';b.textContent='Descarregar diagnóstico';b.onclick=downloadDiagnostic;buttons.appendChild(b)}const state=readState(),meta=readMeta();if(state){const bytes=new Blob([JSON.stringify(state)]).size;panel.querySelector('.fj-backup-summary').innerHTML=`<div class="fj-backup-stat"><small>Registos timeline</small><strong>${state.events?.length||0}</strong></div><div class="fj-backup-stat"><small>Dados locais</small><strong>${formatBytes(bytes)}</strong></div><div class="fj-backup-stat"><small>Último backup</small><strong>${dateLabel(meta.lastBackupAt)}</strong></div>`}const exportBtn=$('#exportBtn');if(exportBtn&&!exportBtn.dataset.fjMeta){exportBtn.dataset.fjMeta='1';exportBtn.addEventListener('click',()=>{const m=readMeta();m.lastBackupAt=Date.now();writeMeta(m)})}const checkBtn=$('#checkBtn');if(checkBtn&&!checkBtn.dataset.fjMeta){checkBtn.dataset.fjMeta='1';checkBtn.addEventListener('click',()=>{const m=readMeta();m.lastDiagnosticAt=Date.now();writeMeta(m)})}}
function restoreView(){const v=sessionStorage.getItem('fj-restore-view');if(!v)return;sessionStorage.removeItem('fj-restore-view');setTimeout(()=>{document.querySelector(`[data-nav="${v}"]`)?.click();if(v==='history'){const d=sessionStorage.getItem('fj-history-date');sessionStorage.removeItem('fj-history-date');if(d&&$('#historyDate')){$('#historyDate').value=d;$('#historyDate').dispatchEvent(new Event('change',{bubbles:true}))}}},30)}
function enhanceAll(){injectStyles();fixVersion();enhanceSettings();enhanceHistory();enhanceBackup()}
function lightTick(){const now=Date.now(),clock=$('#clock');if(clock)clock.textContent=fmtClock(now);const state=readState();if(!state)return;const b=activeBreak(state),f=activeFocus(state),w=activeWork(state);if(f?.status==='ACTIVE'&&Number.isFinite(f.expectedEndAt)&&now>=f.expectedEndAt&&appSecondLoop){appSecondLoop();setTimeout(enhanceAll,0);return}if(b){const timer=$('.hero.break .timer');if(timer){const r=Math.max(0,(b.expectedEndAt??now)-now),o=Math.max(0,now-(b.expectedEndAt??now));timer.textContent=r?fmtDuration(r):'+'+fmtDuration(o)}}else if(f){const remain=focusRemaining(f,now),hero=$('.hero.focus .timer'),stage=$('.focus-ring strong');if(hero)hero.textContent=fmtDuration(remain);if(stage)stage.textContent=fmtDuration(remain);const ring=$('.focus-ring');if(ring){const pct=Math.min(100,Math.max(0,100-remain/(f.targetDurationMs||1)*100));ring.style.setProperty('--p',`${pct*3.6}deg`)}}else if(w){const timer=$('.hero.work .timer');if(timer)timer.textContent=fmtDuration(now-w.startedAt);const breaks=breakMsForWork(state,w,now),eff=Math.max(0,now-w.startedAt-breaks),effective=$('.hero.work .hero-grid div:nth-child(2) b'),pauses=$('.hero.work .hero-grid div:nth-child(3) b');if(effective)effective.textContent=fmtShort(eff);if(pauses)pauses.textContent=fmtShort(breaks)}}

migrateCoffeeDefaults();enhanceAll();observeVersion();restoreView();document.addEventListener('click',()=>setTimeout(enhanceAll,0));document.addEventListener('change',()=>setTimeout(enhanceAll,0));document.addEventListener('submit',()=>setTimeout(enhanceAll,0));nativeSetInterval(lightTick,1000);lightTick();
