import test from 'node:test';import assert from 'node:assert/strict';import * as C from '../core.js';
const t0=Date.UTC(2026,7,18,8,0,0);
function s(){const x=C.createInitialState(t0);x.settings.onboardingDone=true;return x}
test('jornada inicia e impede duplicada',()=>{const x=s();assert.equal(C.startWork(x,t0).ok,true);assert.equal(C.startWork(x,t0+1000).error,'WORK_SESSION_ALREADY_ACTIVE')});
test('jornada termina',()=>{const x=s();const w=C.startWork(x,t0).value;const r=C.endWork(x,t0+8*C.MS.hour);assert.equal(r.ok,true);assert.equal(w.status,'COMPLETED');assert.equal(C.grossWorkMs(w,t0+8*C.MS.hour),8*C.MS.hour)});
test('jornada atravessa meia-noite',()=>{const x=s();const start=Date.UTC(2026,7,18,22),end=Date.UTC(2026,7,19,6);const w=C.startWork(x,start).value;C.endWork(x,end);assert.equal(C.grossWorkMs(w,end),8*C.MS.hour)});
test('pausa é descontada do efetivo',()=>{const x=s();const w=C.startWork(x,t0).value;C.startBreak(x,'SCREEN',t0+C.MS.hour,15);C.endBreak(x,null,t0+C.MS.hour+15*C.MS.minute);C.endWork(x,t0+2*C.MS.hour);assert.equal(C.effectiveWorkMs(x,w,t0+2*C.MS.hour),105*C.MS.minute)});
test('pausa pausa atividade automaticamente',()=>{const x=s();C.startWork(x,t0);const a=C.createActivity(x,{title:'Teste'},t0).value;C.startActivity(x,a.id,t0+1000);C.startBreak(x,'SCREEN',t0+60_000,15);assert.equal(a.status,'PAUSED');assert.equal(C.activeActivitySegment(x),null)});
test('atividade soma segmentos',()=>{const x=s();C.startWork(x,t0);const a=C.createActivity(x,{title:'A'},t0).value;C.startActivity(x,a.id,t0);C.pauseActivity(x,a.id,t0+20*C.MS.minute);C.startActivity(x,a.id,t0+40*C.MS.minute);C.pauseActivity(x,a.id,t0+50*C.MS.minute);assert.equal(C.activityDurationMs(x,a.id,t0+60*C.MS.minute),30*C.MS.minute)});
test('pomodoro pausa sem consumir tempo',()=>{const x=s();C.startWork(x,t0);const f=C.startFocus(x,t0,{durationMinutes:25}).value;C.pauseFocus(x,t0+5*C.MS.minute);assert.equal(C.focusRemainingMs(f,t0+15*C.MS.minute),20*C.MS.minute);C.resumeFocus(x,t0+15*C.MS.minute);assert.equal(f.expectedEndAt,t0+35*C.MS.minute)});
test('foco bloqueia pausa',()=>{const x=s();C.startWork(x,t0);C.startFocus(x,t0);assert.equal(C.startBreak(x,'SCREEN',t0+1000).error,'FOCUS_ALREADY_ACTIVE')});
test('café usa cêntimos inteiros',()=>{const x=s();const c=C.addCoffee(x,t0,{typeId:'espresso',quantity:3}).value;assert.equal(c.totalPriceCents,210);assert.equal(C.dayStats(x,C.localDayKey(t0),t0).coffeeSpend,210)});
test('undo café remove entrada',()=>{const x=s();const c=C.addCoffee(x,t0,{}).value;assert.equal(C.undoCoffee(x,c.id,t0+1).ok,true);assert.equal(x.coffeeEntries.length,0)});
test('edição de jornada valida intervalo',()=>{const x=s();const w=C.startWork(x,t0).value;assert.equal(C.editWork(x,w.id,{startedAt:t0+1000,endedAt:t0},t0).error,'INVALID_TIME_RANGE')});
test('reabrir jornada concluída',()=>{const x=s();const w=C.startWork(x,t0).value;C.endWork(x,t0+C.MS.hour);assert.equal(C.reopenWork(x,w.id,t0+2*C.MS.hour).ok,true);assert.equal(w.status,'ACTIVE')});
test('diagnóstico deteta múltiplas jornadas',()=>{const x=s();x.workSessions.push({id:'a',contextId:'work',status:'ACTIVE',startedAt:t0,endedAt:null},{id:'b',contextId:'work',status:'ACTIVE',startedAt:t0,endedAt:null});assert.equal(C.validateState(x,t0).some(i=>i.code==='MULTIPLE_ACTIVE_WORK'),true)});
test('migração v3 preserva jornada e tarefas',()=>{const old={v:3,settings:{screen:15,rest:60,focus:25,coffee:70},work:[{id:'w',status:'COMPLETED',start:t0,end:t0+C.MS.hour}],tasks:[{id:'a',title:'Antiga',status:'COMPLETED',created:t0,done:t0+C.MS.minute,segments:[]}],breaks:[],focus:[],coffee:[],events:[]};const x=C.migrateState(old,t0);assert.equal(x.schemaVersion,4);assert.equal(x.workSessions.length,1);assert.equal(x.activities[0].title,'Antiga')});
test('estatísticas não somam foco ao trabalho',()=>{const x=s();C.startWork(x,t0);C.startFocus(x,t0,{durationMinutes:25});C.endFocus(x,t0+25*C.MS.minute);C.endWork(x,t0+C.MS.hour);const d=C.dayStats(x,C.localDayKey(t0),t0+C.MS.hour);assert.equal(d.grossWork,C.MS.hour);assert.equal(d.focusTime,25*C.MS.minute)});
