import test from 'node:test';
import assert from 'node:assert/strict';
import {buildMoovitNearbyUrl,buildMoovitDirectionsUrl,computeProjectedExit,summarizeDay,MS} from '../features-core.js';

test('Moovit nearby usa partner e coordenadas válidas',()=>{const u=buildMoovitNearbyUrl({lat:38.72,lon:-9.14});assert.match(u,/moovit:\/\/nearby/);assert.match(u,/lat=38.72/);assert.match(u,/partner_id=FocoJornada/)});
test('Moovit directions omite origem atual e inclui destino',()=>{const u=buildMoovitDirectionsUrl({destination:{name:'Trabalho',lat:38.7,lon:-9.1}});assert.equal(u.includes('orig_lat'),false);assert.match(u,/dest_name=Trabalho/);assert.match(u,/auto_run=true/)});
test('previsão de saída inclui pausa principal ainda não usada',()=>{const now=Date.UTC(2026,7,19,8,0);const state={settings:{activeContextId:'work'},workSessions:[{id:'w',contextId:'work',status:'ACTIVE',startedAt:now}],breakSessions:[]};const r=computeProjectedExit(state,{targetMinutes:480,plannedRestMinutes:60,now});assert.equal(r.projectedAt,now+9*MS.hour)});
test('previsão deixa de acrescentar descanso após pausa REST',()=>{const now=Date.UTC(2026,7,19,9,0);const state={settings:{activeContextId:'work'},workSessions:[{id:'w',contextId:'work',status:'ACTIVE',startedAt:now-MS.hour}],breakSessions:[{workSessionId:'w',type:'REST',status:'COMPLETED',startedAt:now-30*MS.minute,endedAt:now}]};const r=computeProjectedExit(state,{targetMinutes:480,plannedRestMinutes:60,now});assert.equal(r.plannedRestRemainingMs,0)});
test('resumo diário desconta pausas',()=>{const start=new Date(2026,7,19,8,0).getTime();const state={workSessions:[{id:'w',status:'COMPLETED',startedAt:start,endedAt:start+9*MS.hour}],breakSessions:[{workSessionId:'w',status:'COMPLETED',type:'REST',startedAt:start+4*MS.hour,endedAt:start+5*MS.hour}],focusSessions:[],coffeeEntries:[],activities:[]};const s=summarizeDay(state,'2026-08-19',start+10*MS.hour);assert.equal(s.effectiveWorkMs,8*MS.hour);assert.equal(s.breakMs,MS.hour)});
