import test from 'node:test';
import assert from 'node:assert/strict';
import {
  buildMoovitNearbyUrl,buildMoovitDirectionsUrl,computeProjectedExit,summarizeDay,
  DEFAULT_WEEKLY_SCHEDULE,plannedShift,breakReminderStatus,buildWorkScheduleIcs,
  validCoordinate,MS
} from '../features-core.js';

test('Moovit nearby usa partner e coordenadas válidas',()=>{const u=buildMoovitNearbyUrl({lat:38.72,lon:-9.14});assert.match(u,/moovit:\/\/nearby/);assert.match(u,/lat=38.72/);assert.match(u,/partner_id=FocoJornada/)});
test('Moovit directions omite origem atual e inclui destino',()=>{const u=buildMoovitDirectionsUrl({destination:{name:'Trabalho',lat:38.7,lon:-9.1}});assert.equal(u.includes('orig_lat'),false);assert.match(u,/dest_name=Trabalho/);assert.match(u,/auto_run=true/)});
test('coordenada vazia não é interpretada como zero',()=>{assert.equal(validCoordinate('',-90,90),false);assert.equal(validCoordinate(null,-90,90),false);assert.equal(validCoordinate(0,-90,90),true)});
test('segunda a sábado usam horário 08-17 com pausa 12-13',()=>{for(const day of [1,2,3,4,5,6]){const d=new Date(2026,7,17+day);while(d.getDay()!==day)d.setDate(d.getDate()+1);const p=plannedShift(d,DEFAULT_WEEKLY_SCHEDULE);assert.equal(p.start,'08:00');assert.equal(p.end,'17:00');assert.equal(p.breakStart,'12:00');assert.equal(p.breakEnd,'13:00')}});
test('domingo usa horário 09-18 com pausa 13-14',()=>{const d=new Date(2026,7,23,10,0);assert.equal(d.getDay(),0);const p=plannedShift(d);assert.equal(p.start,'09:00');assert.equal(p.end,'18:00');assert.equal(p.breakStart,'13:00');assert.equal(p.breakEnd,'14:00')});
test('lembrete de pausa exige jornada ativa e confirmação manual',()=>{const now=new Date(2026,7,19,12,5).getTime();const state={settings:{activeContextId:'work'},workSessions:[{id:'w',contextId:'work',status:'ACTIVE',startedAt:new Date(2026,7,19,8,0).getTime()}],breakSessions:[]};assert.equal(breakReminderStatus(state,{now}).shouldRemind,true);assert.equal(breakReminderStatus(state,{now,alreadyReminded:true}).shouldRemind,false)});
test('pausa REST já feita cancela lembrete',()=>{const now=new Date(2026,7,19,12,5).getTime();const state={settings:{activeContextId:'work'},workSessions:[{id:'w',contextId:'work',status:'ACTIVE',startedAt:new Date(2026,7,19,8,0).getTime()}],breakSessions:[{workSessionId:'w',type:'REST',status:'COMPLETED',startedAt:new Date(2026,7,19,11,0).getTime(),endedAt:new Date(2026,7,19,12,0).getTime()}]};assert.equal(breakReminderStatus(state,{now}).shouldRemind,false)});
test('previsão de saída inclui pausa principal ainda não usada',()=>{const now=Date.UTC(2026,7,19,8,0);const state={settings:{activeContextId:'work'},workSessions:[{id:'w',contextId:'work',status:'ACTIVE',startedAt:now}],breakSessions:[]};const r=computeProjectedExit(state,{targetMinutes:480,plannedRestMinutes:60,now});assert.equal(r.projectedAt,now+9*MS.hour)});
test('previsão deixa de acrescentar descanso após pausa REST',()=>{const now=Date.UTC(2026,7,19,9,0);const state={settings:{activeContextId:'work'},workSessions:[{id:'w',contextId:'work',status:'ACTIVE',startedAt:now-MS.hour}],breakSessions:[{workSessionId:'w',type:'REST',status:'COMPLETED',startedAt:now-30*MS.minute,endedAt:now}]};const r=computeProjectedExit(state,{targetMinutes:480,plannedRestMinutes:60,now});assert.equal(r.plannedRestRemainingMs,0)});
test('resumo diário desconta pausas',()=>{const start=new Date(2026,7,19,8,0).getTime();const state={workSessions:[{id:'w',status:'COMPLETED',startedAt:start,endedAt:start+9*MS.hour}],breakSessions:[{workSessionId:'w',status:'COMPLETED',type:'REST',startedAt:start+4*MS.hour,endedAt:start+5*MS.hour}],focusSessions:[],coffeeEntries:[],activities:[]};const s=summarizeDay(state,'2026-08-19',start+10*MS.hour);assert.equal(s.effectiveWorkMs,8*MS.hour);assert.equal(s.breakMs,MS.hour)});
test('exportação ICS inclui turnos e pausa prevista para Supershift/calendário externo',()=>{const ics=buildWorkScheduleIcs({startDate:new Date(2026,7,23,9,0),weeks:1});assert.match(ics,/BEGIN:VCALENDAR/);assert.match(ics,/DTSTART:20260823T090000/);assert.match(ics,/DTEND:20260823T180000/);assert.match(ics,/Pausa prevista 13:00–14:00/);assert.match(ics,/END:VCALENDAR/)});
