import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');

test('tipografia pública usa uma pilha local estável',()=>{const css=read('linear-ui.css');assert.ok(css.includes('font-family:ui-sans-serif,-apple-system,BlinkMacSystemFont'));assert.ok(css.includes('html,body,button,input,select,textarea'));assert.ok(css.includes('-webkit-font-smoothing:antialiased'));assert.equal(css.includes('font-family:"Manrope"'),false);assert.equal(css.includes('font-weight:650'),false);});
test('Flaticon UIcons é melhoria opcional com fallback local',()=>{const html=read('index.html'),icons=read('flaticon-icons.js'),motion=read('flaticon-motion.css');assert.ok(html.includes('cdn-uicons.flaticon.com/4.0.0/uicons-regular-rounded'));assert.ok(html.includes('data-flaticon-uicons'));assert.ok(html.includes('href="./flaticon-motion.css"'));assert.ok(html.includes('src="./flaticon-icons.js"'));assert.ok(icons.includes("FLATICON_VERSION='4.0.0'"));assert.ok(icons.includes('flaticon-source-hidden'));assert.ok(motion.includes('width:1em;height:1em;flex:0 0 1em'));assert.ok(motion.includes('.flaticon-source-hidden{display:none!important}'));});
test('Planeamento usa o mesmo ícone Flaticon em todas as entradas',()=>{const html=read('index.html'),icons=read('flaticon-icons.js'),planning=read('planning-mode.js');assert.ok(html.includes('data-view="planning"'));assert.ok(html.includes('data-nav="planning"'));assert.ok(icons.includes("planning:'calendar-lines'"));assert.ok(icons.includes("goFocus:'calendar-lines'"));assert.ok(icons.includes("planning:'calendar-lines',stats"));assert.ok(planning.includes('planning-glyph'));assert.equal(html.includes('src="./focus-mode.js"'),false);assert.equal(html.includes('./focus-mode.css'),false);});
test('camada de estabilidade mantém alvos de toque grandes',()=>{const css=read('stability-ui.css');for(const value of ['.bottom-nav .ui-svg{width:36px;height:36px}', '.quick-grid>button>span .ui-svg{width:48px;height:48px}', '.icon-btn .ui-svg{width:28px;height:28px}', '.hub-item-icon .hub-svg{width:28px;height:28px}', '.transport-launch-icon .feature-svg{width:34px;height:34px}', '.shift-planner .sp-top-actions button,.shift-planner .sp-close{width:44px;height:44px'])assert.ok(css.includes(value),value);assert.ok(css.includes('@media(prefers-reduced-motion:reduce)'));});
test('folhas dinâmicas principais chegam carregadas uma única vez',()=>{const html=read('index.html'),features=read('features.js'),about=read('hub-about.js');assert.ok(html.includes('id="featuresCss"'));assert.ok(features.includes("if($('#featuresCss'))return"));assert.ok(html.includes('id="hubAboutCss"'));assert.ok(about.includes("document.querySelector('#hubAboutCss')"));});
test('Service Worker e Pages publicam apenas uma versão previamente validada',()=>{const sw=read('sw.js'),pages=read('.github/workflows/pages.yml');for(const file of ['./stability-ui.css','./planning-mode.js','./flaticon-motion.css','./flaticon-icons.js'])assert.ok(sw.includes(file),`cache ${file}`);for(const file of ['planning-mode.js','flaticon-motion.css','flaticon-icons.js'])assert.ok(pages.includes(file),`pages ${file}`);assert.equal(sw.includes('focus-mode.js'),false);assert.equal(pages.includes('focus-mode.js'),false);assert.ok(sw.includes('stability2'));assert.ok(pages.includes('workflow_run'));assert.ok(pages.includes('github.event.workflow_run.conclusion == \'success\''));assert.ok(pages.includes('Confirmar testes antes da publicação'));});
