import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
test('menu Mais carrega o hub oculto',()=>{const index=read('index.html');assert.ok(index.includes('./hub.css'));assert.ok(index.includes('src="./hub.js"'));});
test('hub contém acessos rápidos e ferramentas reais da aplicação',()=>{const hub=read('hub.js');for(const item of ['Moovit','Supershift','Escala de trabalho','Atividades','Foco e Pomodoro','Definições','Backup e diagnóstico','Notificações','Atualizações','Ajuda','Sobre'])assert.ok(hub.includes(item),item);});
test('Moovit mantém deep link oficial e hub direciona para o planeador interno',()=>{const hub=read('hub.js');assert.ok(hub.includes('moovit://nearby?partner_id=FocoJornada'));assert.ok(hub.includes('moovit.onelink.me/3986059930'));assert.ok(hub.includes("openIntegration('moovitSection')"));});
test('Supershift do hub abre o módulo interno completo',()=>{const hub=read('hub.js');assert.ok(hub.includes("import('./shift-planner.js')"));assert.ok(hub.includes('openShiftPlanner'));assert.equal(hub.includes('supershift://'),false);});
test('hub não cria polling contínuo',()=>assert.equal(read('hub.js').includes('setInterval('),false));
test('hub mantém acesso à página Mais original',()=>{const hub=read('hub.js');assert.ok(hub.includes('bypassMore'));assert.ok(hub.includes("openMoreAt('#settingsForm')"));assert.ok(hub.includes("openMoreAt('#exportBtn')"));});
test('hub mobile usa painel de ecrã completo e hierarquia em listas',()=>{const css=read('hub.css');assert.ok(css.includes('height:100dvh'));assert.ok(css.includes('.hub-list'));assert.ok(css.includes('.hub-quick'));assert.ok(css.includes('.hub-help'));});
