import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
test('menu Mais mantém CSS e é carregado diretamente após o núcleo',()=>{const index=read('index.html');assert.ok(index.includes('./hub.css'));assert.ok(index.includes('src="./ux.js"'));assert.ok(index.includes('src="./hub.js"'));assert.ok(index.indexOf('src="./persistence.js"')<index.indexOf('src="./ux.js"'));assert.ok(index.indexOf('src="./ux.js"')<index.indexOf('src="./hub.js"'));assert.equal(index.includes("import('./bootstrap.js')"),false);});
test('hub contém todas as categorias principais',()=>{const hub=read('hub.js');for(const item of ['Principal','Trabalho','Produtividade','Transportes','Dados e aplicação','Informação'])assert.ok(hub.includes(item),item);});
test('hub contém destinos funcionais da aplicação',()=>{const hub=read('hub.js');for(const item of ['Hoje','Atividades','Foco e Pomodoro','Histórico','Estatísticas','Supershift / Escala','Horário e pausas','Moovit','Notificações','Definições','Backup e diagnóstico','Atualizações','Ajuda','Sobre'])assert.ok(hub.includes(item),item);});
test('pesquisa do menu filtra opções e categorias',()=>{const hub=read('hub.js');assert.ok(hub.includes('id="hubSearch"'));assert.ok(hub.includes('function filterMenu'));assert.ok(hub.includes('data-hub-search'));});
test('menu não abre teclado automaticamente',()=>{const hub=read('hub.js');assert.equal(hub.includes("$('#hubSearch')?.focus()"),false);});
test('Moovit mantém deep link oficial e menu direciona para o planeador interno',()=>{const hub=read('hub.js');assert.ok(hub.includes('moovit://nearby?partner_id=FocoJornada'));assert.ok(hub.includes('moovit.onelink.me/3986059930'));assert.ok(hub.includes("openIntegration('moovitSection')"));});
test('Supershift abre o módulo interno completo',()=>{const hub=read('hub.js');assert.ok(hub.includes("import('./shift-planner.js')"));assert.ok(hub.includes('openShiftPlanner'));assert.equal(hub.includes('supershift://'),false);});
test('hub não cria polling contínuo',()=>assert.equal(read('hub.js').includes('setInterval('),false));
test('menu mobile é lateral simples',()=>{const css=read('hub.css');assert.ok(css.includes('translateX(-102%)'));assert.ok(css.includes('.hub-search'));assert.ok(css.includes('.hub-category'));assert.ok(css.includes('.hub-item'));});
test('hub mantém acesso à página Mais original',()=>{const hub=read('hub.js');assert.ok(hub.includes('bypassMore'));assert.ok(hub.includes("openMoreAt('#settingsForm')"));assert.ok(hub.includes("openMoreAt('#exportBtn')"));});
