import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
test('menu Mais carrega o hub oculto',()=>{const index=read('index.html');assert.ok(index.includes('./hub.css'));assert.ok(index.includes('src="./hub.js"'));});
test('hub contém Moovit, Supershift e ferramentas do sistema',()=>{const hub=read('hub.js');for(const item of ['Moovit','Supershift','Escala de trabalho','Definições','Backup e diagnóstico','Notificações','Atualizações'])assert.ok(hub.includes(item),item);});
test('Moovit continua a abrir por deep link oficial com fallback',()=>{const hub=read('hub.js');assert.ok(hub.includes('moovit://nearby?partner_id=FocoJornada'));assert.ok(hub.includes('moovit.onelink.me/3986059930'));});
test('Supershift do hub abre o módulo interno completo',()=>{const hub=read('hub.js');assert.ok(hub.includes("import('./shift-planner.js')"));assert.ok(hub.includes('openShiftPlanner'));assert.equal(hub.includes('supershift://'),false);});
test('hub não cria polling contínuo',()=>assert.equal(read('hub.js').includes('setInterval('),false));
test('hub mantém acesso à página Mais original',()=>{const hub=read('hub.js');assert.ok(hub.includes('bypassMore'));assert.ok(hub.includes("openMoreAt('#settingsForm')"));assert.ok(hub.includes("openMoreAt('#exportBtn')"));});
